export const PROCEDIMENTOS = [
  "Restaurações","Limpezas","Clareamento","Cirurgias",
  "Implantes","Ortodontia","Invisa","Placas",
  "Lentes Porcelana","Lentes Resina","Endodontia","Próteses"
]

export const PROC_CFG = [
  { key:"Cirurgias",        icon:"✂️",  color:"#dc2626", bg:"#fef2f2", label:"Cirurgias"        },
  { key:"Implantes",        icon:"🔩",  color:"#7c3aed", bg:"#f5f3ff", label:"Implantes"        },
  { key:"Ortodontia",       icon:"📐",  color:"#1d6fd8", bg:"#eff6ff", label:"Ortodontia"       },
  { key:"Restaurações",     icon:"🦷",  color:"#0d9488", bg:"#f0fdfa", label:"Restaurações"     },
  { key:"Limpezas",         icon:"✨",  color:"#16a34a", bg:"#f0fdf4", label:"Limpezas"         },
  { key:"Clareamento",      icon:"⚡",  color:"#ca8a04", bg:"#fefce8", label:"Clareamento"      },
  { key:"Próteses",         icon:"🦴",  color:"#ea580c", bg:"#fff7ed", label:"Próteses"         },
  { key:"Endodontia",       icon:"🩺",  color:"#be185d", bg:"#fdf2f8", label:"Endodontia"       },
  { key:"Lentes Porcelana", icon:"💎",  color:"#0369a1", bg:"#f0f9ff", label:"Lentes Porcelana" },
  { key:"Lentes Resina",    icon:"💎",  color:"#4f46e5", bg:"#eef2ff", label:"Lentes Resina"    },
  { key:"Invisa",           icon:"👁",  color:"#0891b2", bg:"#ecfeff", label:"Invisalign"       },
  { key:"Placas",           icon:"🛡",  color:"#65a30d", bg:"#f7fee7", label:"Placas"           },
]

export const STATUS_AV = ["Aprovado","Faltou","Em Aberto","Follow Up","Reprovado","Pendente"]

export const STATUS_CFG = {
  "Aprovado":  { color:"#16a34a", bg:"#f0fdf4", border:"#bbf7d0" },
  "Faltou":    { color:"#dc2626", bg:"#fef2f2", border:"#fecaca" },
  "Em Aberto": { color:"#7c3aed", bg:"#f5f3ff", border:"#ddd6fe" },
  "Follow Up": { color:"#1d6fd8", bg:"#eff6ff", border:"#bfdbfe" },
  "Reprovado": { color:"#be185d", bg:"#fdf2f8", border:"#fbcfe8" },
  "Pendente":  { color:"#ca8a04", bg:"#fefce8", border:"#fef08a" },
}

export const MESES = [
  "Janeiro","Fevereiro","Março","Abril","Maio","Junho",
  "Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"
]

// Dados iniciais para popular o banco na primeira vez
export const SEED_PACIENTES = [
  { id:"j1",  nome:"José do Lago",              mes:"Janeiro",   procs:{ Limpezas:"1" },                                                                           feitos:{}, obs:"" },
  { id:"j2",  nome:"Adriele Cheregati",          mes:"Janeiro",   procs:{ Restaurações:"16" },                                                                      feitos:{}, obs:"" },
  { id:"j3",  nome:"Jawad Ataya",                mes:"Janeiro",   procs:{ Limpezas:"1" },                                                                           feitos:{}, obs:"" },
  { id:"j4",  nome:"Alaa Ataya",                 mes:"Janeiro",   procs:{ Limpezas:"1" },                                                                           feitos:{}, obs:"" },
  { id:"j5",  nome:"Geisy Kelli da Silva",       mes:"Janeiro",   procs:{ Restaurações:"11.12.14.17.44.45", Limpezas:"1" },                                         feitos:{}, obs:"" },
  { id:"j6",  nome:"Liliana Andréia Guimarães",  mes:"Janeiro",   procs:{ Restaurações:"46", Limpezas:"1", Clareamento:"Gengivectimia", Cirurgias:"25", Ortodontia:"Estético", Próteses:"Coroa Provisória" }, feitos:{}, obs:"" },
  { id:"j7",  nome:"Ana Clara Gentil",           mes:"Janeiro",   procs:{ Restaurações:"13.14.24.16", Limpezas:"1", Ortodontia:"Estético" },                        feitos:{}, obs:"" },
  { id:"j8",  nome:"Rosa Helena Ferreira",       mes:"Janeiro",   procs:{ Restaurações:"18.28.27.25", Limpezas:"1" },                                              feitos:{}, obs:"" },
  { id:"j9",  nome:"Rodrigo Benatti Dias",       mes:"Janeiro",   procs:{ Restaurações:"47", Limpezas:"1", Cirurgias:"28", Ortodontia:"Convencional" },             feitos:{}, obs:"" },
  { id:"j10", nome:"Nathalie Prieto de Morais",  mes:"Janeiro",   procs:{ Restaurações:"11.16.17.12.22", Limpezas:"1" },                                           feitos:{}, obs:"" },
  { id:"j11", nome:"Juliana Cristina Gino",      mes:"Janeiro",   procs:{ Restaurações:"14", Limpezas:"1", Cirurgias:"28.38" },                                    feitos:{}, obs:"" },
  { id:"j12", nome:"Kevin Rian Fernandes",       mes:"Janeiro",   procs:{ Limpezas:"1" },                                                                          feitos:{}, obs:"" },
  { id:"j13", nome:"Itamar Soler Martins",       mes:"Janeiro",   procs:{ Restaurações:"26.17", Limpezas:"1", Ortodontia:"Convencional" },                         feitos:{}, obs:"" },
  { id:"j14", nome:"Livia Maria de Oliveira",    mes:"Janeiro",   procs:{ Ortodontia:"Convencional" },                                                             feitos:{}, obs:"" },
  { id:"j15", nome:"Jozenilda dos Santos",       mes:"Janeiro",   procs:{},                                                                                        feitos:{}, obs:"" },
  { id:"j16", nome:"Eduardo Antônio Ferrari",    mes:"Janeiro",   procs:{ Limpezas:"1" },                                                                          feitos:{}, obs:"" },
  { id:"j17", nome:"Carlos Eduardo Módena",      mes:"Janeiro",   procs:{ Restaurações:"17.35", Limpezas:"1" },                                                    feitos:{}, obs:"" },
  { id:"f1",  nome:"Taina de Campos",            mes:"Fevereiro", procs:{ "Lentes Resina":"11.21" },                                                               feitos:{}, obs:"" },
  { id:"f2",  nome:"Willian Gomes",              mes:"Fevereiro", procs:{ Restaurações:"21.11.16.46", Limpezas:"1" },                                              feitos:{}, obs:"" },
  { id:"f3",  nome:"Henrique do Carmo",          mes:"Fevereiro", procs:{ "Lentes Porcelana":"25" },                                                               feitos:{}, obs:"" },
  { id:"f4",  nome:"André Mariano",              mes:"Fevereiro", procs:{ Limpezas:"1", "Lentes Resina":"23" },                                                    feitos:{}, obs:"" },
  { id:"f5",  nome:"Bernardo Bergamin",          mes:"Fevereiro", procs:{ Restaurações:"75", Limpezas:"1", Ortodontia:"Ortopédico" },                              feitos:{}, obs:"" },
  { id:"f6",  nome:"Magna Oliveira",             mes:"Fevereiro", procs:{ Restaurações:"23", Endodontia:"23" },                                                    feitos:{}, obs:"" },
  { id:"f7",  nome:"Bruno Eduardo Vieira",       mes:"Fevereiro", procs:{ Limpezas:"1", Ortodontia:"Contenção" },                                                  feitos:{}, obs:"" },
  { id:"f8",  nome:"Adriano Furigo",             mes:"Fevereiro", procs:{ Restaurações:"21", Limpezas:"1" },                                                       feitos:{}, obs:"" },
  { id:"f9",  nome:"Rosemary da Silva Teodoro",  mes:"Fevereiro", procs:{ Restaurações:"46", Limpezas:"1", "Lentes Resina":"11.21" },                              feitos:{}, obs:"" },
  { id:"f10", nome:"Evelin Lusa",                mes:"Fevereiro", procs:{ Limpezas:"1" },                                                                          feitos:{}, obs:"" },
  { id:"f11", nome:"Josiane Cristina",           mes:"Fevereiro", procs:{ Restaurações:"26.22.11", Limpezas:"1", Endodontia:"18" },                                feitos:{}, obs:"" },
  { id:"f12", nome:"Cicelio do Nascimento",      mes:"Fevereiro", procs:{ Restaurações:"12.21.47", Limpezas:"2", Clareamento:"Por elemento", Cirurgias:"45", Implantes:"45", "Lentes Resina":"11", Endodontia:"35", Próteses:"35" }, feitos:{}, obs:"" },
  { id:"f13", nome:"Josuel dos Santos",          mes:"Fevereiro", procs:{ Restaurações:"45.21", Limpezas:"3" },                                                    feitos:{}, obs:"" },
  { id:"f14", nome:"Isabelly de Oliveira",       mes:"Fevereiro", procs:{ Cirurgias:"48.28" },                                                                     feitos:{}, obs:"" },
  { id:"f15", nome:"Lenita A. Scomparin",        mes:"Fevereiro", procs:{ Implantes:"1" },                                                                         feitos:{}, obs:"" },
  { id:"f16", nome:"Amanda Godoi",               mes:"Fevereiro", procs:{ Restaurações:"36", Limpezas:"1" },                                                       feitos:{}, obs:"" },
  { id:"f17", nome:"Pedro Scomparin",            mes:"Fevereiro", procs:{ Restaurações:"17.26.27", Limpezas:"1" },                                                 feitos:{}, obs:"" },
  { id:"f18", nome:"Robson Gimenez",             mes:"Fevereiro", procs:{ Restaurações:"34.35.23.24.25.14.15.44.45.16", Limpezas:"1", Cirurgias:"46.27", Ortodontia:"Convencional" }, feitos:{}, obs:"" },
  { id:"f19", nome:"Karina Martins",             mes:"Fevereiro", procs:{ "Lentes Porcelana":"31-45" },                                                            feitos:{}, obs:"" },
  { id:"f20", nome:"Anderson Pereira",           mes:"Fevereiro", procs:{ Restaurações:"43.44.34.37.46", Limpezas:"1" },                                           feitos:{}, obs:"" },
  { id:"f21", nome:"Francisco Correa",           mes:"Fevereiro", procs:{ Restaurações:"21.27.46", Limpezas:"1" },                                                 feitos:{}, obs:"" },
  { id:"f22", nome:"Bruno Henrique",             mes:"Fevereiro", procs:{ Restaurações:"13.44.46.35.27.17", Limpezas:"1", Cirurgias:"38.48" },                     feitos:{}, obs:"" },
  { id:"f23", nome:"José Carlos Moreira",        mes:"Fevereiro", procs:{ Cirurgias:"Tracionamento 23" },                                                          feitos:{}, obs:"" },
  { id:"f24", nome:"Robson Beserra",             mes:"Fevereiro", procs:{ Invisa:"Contenção inf" },                                                                feitos:{}, obs:"" },
  { id:"m1",  nome:"Robinson Aparecido da Silva",mes:"Março",     procs:{ Restaurações:"11.21.26.36.31", Limpezas:"1", Cirurgias:"18.28.38.48", Ortodontia:"Convencional" }, feitos:{}, obs:"" },
  { id:"m2",  nome:"Sérgio Luis da Silva",       mes:"Março",     procs:{ Restaurações:"26.16", Limpezas:"1" },                                                    feitos:{}, obs:"" },
  { id:"m3",  nome:"Jean Moacir Casaril",        mes:"Março",     procs:{ Restaurações:"36.26.17", Limpezas:"1", "Lentes Resina":"13" },                           feitos:{}, obs:"" },
  { id:"m4",  nome:"Elis Regina Sousa",          mes:"Março",     procs:{ Restaurações:"11.14.16.45.26.34.35.36.46", Limpezas:"1", Cirurgias:"18.28.38", Ortodontia:"Convencional" }, feitos:{}, obs:"" },
  { id:"m5",  nome:"Joao Fernando Pangalde",     mes:"Março",     procs:{ Restaurações:"12.13.21", Limpezas:"1", Cirurgias:"Exo" },                                feitos:{}, obs:"" },
  { id:"m6",  nome:"Ana Lívia Faria da Silva",   mes:"Março",     procs:{ Restaurações:"46.47.21.36.37.26", Limpezas:"1" },                                        feitos:{}, obs:"" },
  { id:"m7",  nome:"Pietro Niller Mello",        mes:"Março",     procs:{ Restaurações:"23", Limpezas:"1", Invisa:"lite" },                                        feitos:{}, obs:"" },
  { id:"m8",  nome:"Diego Arita",                mes:"Março",     procs:{ Restaurações:"46.15.37", Limpezas:"1", Cirurgias:"Aumento de coroa" },                   feitos:{}, obs:"" },
  { id:"m9",  nome:"José Ap. Balanciele",        mes:"Março",     procs:{ Próteses:"Total" },                                                                      feitos:{}, obs:"" },
  { id:"m10", nome:"Suely F. S. Marineri",       mes:"Março",     procs:{ Restaurações:"25.37", Limpezas:"1", Cirurgias:"35" },                                    feitos:{}, obs:"" },
  { id:"m11", nome:"Eduardo Antônio Ferrari",    mes:"Março",     procs:{ Limpezas:"1", Cirurgias:"14", Invisa:"Comprehensive", Próteses:"Coroa Prov" },           feitos:{}, obs:"" },
  { id:"m12", nome:"Rafaela Amaro de Carvalho",  mes:"Março",     procs:{ Restaurações:"25", Ortodontia:"Convencional" },                                          feitos:{}, obs:"" },
  { id:"m13", nome:"Liliana Andréia Guimarães",  mes:"Março",     procs:{ Clareamento:"Caseiro/Consultório" },                                                     feitos:{}, obs:"" },
  { id:"m14", nome:"Cátia Gonçalves Cabral",     mes:"Março",     procs:{ Limpezas:"1", "Lentes Resina":"15" },                                                    feitos:{}, obs:"" },
  { id:"m15", nome:"Anderson Jesus Batista",     mes:"Março",     procs:{ Restaurações:"26.17.11.22.24", Limpezas:"1", Próteses:"Coroa 16" },                      feitos:{}, obs:"" },
  { id:"m16", nome:"Lucas Natan Mendes",         mes:"Março",     procs:{ Restaurações:"17.27.35.11.21", Limpezas:"1", Cirurgias:"18.28.38.48", "Lentes Resina":"13.14.15" }, feitos:{}, obs:"" },
  { id:"m17", nome:"Andressa Cardoso",           mes:"Março",     procs:{ Restaurações:"46.47" },                                                                  feitos:{}, obs:"" },
  { id:"m18", nome:"Karina Teobaldo",            mes:"Março",     procs:{ Ortodontia:"Contenção" },                                                                feitos:{}, obs:"" },
  { id:"a1",  nome:"Vivian Gallego Arruda",      mes:"Abril",     procs:{ Ortodontia:"Convencional" },                                                             feitos:{}, obs:"" },
  { id:"a2",  nome:"Asafe Emanuel Matos Gama",   mes:"Abril",     procs:{ Restaurações:"46.47.27", Limpezas:"1", Ortodontia:"Estético" },                          feitos:{}, obs:"" },
  { id:"a3",  nome:"Ivanilda Leite de Souza",    mes:"Abril",     procs:{ Restaurações:"45.25.26", Limpezas:"1", Clareamento:"1" },                                feitos:{}, obs:"" },
  { id:"a4",  nome:"Gislene Freitas de Camargo", mes:"Abril",     procs:{ Restaurações:"11.15.24.25", Limpezas:"1", Ortodontia:"Estético", Endodontia:"25" },      feitos:{}, obs:"" },
  { id:"a5",  nome:"Jael Gomes Haine",           mes:"Abril",     procs:{ Restaurações:"16.37", Limpezas:"1", Cirurgias:"46.36" },                                 feitos:{}, obs:"" },
  { id:"a6",  nome:"Vanessa de Souza Lima",      mes:"Abril",     procs:{ Restaurações:"15", Limpezas:"1", Cirurgias:"18.28.48" },                                 feitos:{}, obs:"" },
  { id:"a7",  nome:"Mayara Ferreira Marques",    mes:"Abril",     procs:{ Restaurações:"11.21.17.24", Limpezas:"1", Cirurgias:"18.38.48", Ortodontia:"Convencional" }, feitos:{}, obs:"" },
  { id:"a8",  nome:"João Carlos Elias de Campo", mes:"Abril",     procs:{ Restaurações:"14.15.16.36.45", Limpezas:"1", Implantes:"21", Endodontia:"23", Próteses:"21 Coroa" }, feitos:{}, obs:"" },
  { id:"a9",  nome:"André Luiz Gozzi Joaquim",   mes:"Abril",     procs:{ Cirurgias:"Enxerto", Implantes:"21.23" },                                                feitos:{}, obs:"" },
  { id:"a10", nome:"Paulo José Franco",          mes:"Abril",     procs:{ Implantes:"12.15", Próteses:"11-15.21.22 grampo" },                                      feitos:{}, obs:"" },
  { id:"a11", nome:"Thiago Araújo",              mes:"Abril",     procs:{ Limpezas:"1", Implantes:"46.26", "Lentes Resina":"11-24" },                              feitos:{}, obs:"" },
  { id:"a12", nome:"Pâmella Maciel Rodrigues",   mes:"Abril",     procs:{ Restaurações:"16.17.27.36.37.47", Limpezas:"1", Cirurgias:"26", Ortodontia:"Convencional" }, feitos:{}, obs:"" },
  { id:"a13", nome:"Ana Lidia Alves",            mes:"Abril",     procs:{ Restaurações:"11.21.23.24.25.27", Limpezas:"1", Cirurgias:"48.18.38", Ortodontia:"Convencional", Próteses:"36 emax" }, feitos:{}, obs:"" },
  { id:"a14", nome:"Maria Eugenia Martinho",     mes:"Abril",     procs:{ Restaurações:"32.31.33.13.21.23.41", Cirurgias:"27.15", Próteses:"PPR" },                feitos:{}, obs:"" },
  { id:"a15", nome:"Inês Ferreira de Lima",      mes:"Abril",     procs:{ Limpezas:"1" },                                                                          feitos:{}, obs:"" },
  { id:"mi1", nome:"Felipe de Castro Silveira",  mes:"Maio",      procs:{ Ortodontia:"Ortopédico" },                                                               feitos:{}, obs:"" },
  { id:"mi2", nome:"Iolanda Ap. Gonçalves",      mes:"Maio",      procs:{ "Lentes Resina":"17", Próteses:"Coroa emax 46" },                                        feitos:{}, obs:"" },
  { id:"mi3", nome:"Elizabethe de Melo",         mes:"Maio",      procs:{ Próteses:"Coroa 11" },                                                                   feitos:{}, obs:"" },
  { id:"mi4", nome:"Ana Laura Borin",            mes:"Maio",      procs:{ Ortodontia:"Convencional" },                                                             feitos:{}, obs:"" },
  { id:"mi5", nome:"Josefa Severina Torres",     mes:"Maio",      procs:{ Limpezas:"1", Clareamento:"1", Cirurgias:"46", Ortodontia:"Contenção" },                 feitos:{}, obs:"" },
  { id:"mi6", nome:"Charles Kelvin Paulino",     mes:"Maio",      procs:{ Restaurações:"14", Endodontia:"14" },                                                    feitos:{}, obs:"" },
  { id:"mi7", nome:"Lucas Roberto",              mes:"Maio",      procs:{ Restaurações:"15.16.24.34.44.35", Limpezas:"1", Ortodontia:"Auto Ligado", Próteses:"Coroa Prov 37" }, feitos:{}, obs:"" },
  { id:"mi8", nome:"Celso Benatti",              mes:"Maio",      procs:{ Endodontia:"34", Próteses:"Coroa emax 34" },                                             feitos:{}, obs:"" },
  { id:"mi9", nome:"Mariane Souza da Cruz",      mes:"Maio",      procs:{ Restaurações:"16.17.36.37", Limpezas:"1", Clareamento:"Inferior", Cirurgias:"Gengivectomia", "Lentes Resina":"11-25" }, feitos:{}, obs:"" },
  { id:"mi10",nome:"Inês Ferreira de Lima",      mes:"Maio",      procs:{ Restaurações:"13.31.35.41.46" },                                                         feitos:{}, obs:"" },
  { id:"mi11",nome:"Gabriella Christina Miguel", mes:"Maio",      procs:{ Limpezas:"1", Ortodontia:"Invisa" },                                                     feitos:{}, obs:"" },
]

export const SEED_AVALIACOES = [
  { id:"ja1",  nome:"Maycon da Silva Barofe",     mes:"Janeiro",   data:"14/01/2026", status:"Pendente",  obs:"" },
  { id:"ja2",  nome:"Rosa Helena Ferreira",       mes:"Janeiro",   data:"14/01/2026", status:"Aprovado",  obs:"" },
  { id:"ja3",  nome:"Gabriel Rossi",              mes:"Janeiro",   data:"14/01/2026", status:"Faltou",    obs:"" },
  { id:"ja4",  nome:"Liliana Andréia Guimarães",  mes:"Janeiro",   data:"15/01/2026", status:"Aprovado",  obs:"" },
  { id:"ja5",  nome:"Adriele Cheregati",          mes:"Janeiro",   data:"15/01/2026", status:"Aprovado",  obs:"" },
  { id:"ja6",  nome:"Geisy Kelli da Silva",       mes:"Janeiro",   data:"15/01/2026", status:"Aprovado",  obs:"" },
  { id:"ja7",  nome:"Itamar Soler",               mes:"Janeiro",   data:"20/01/2026", status:"Aprovado",  obs:"" },
  { id:"ja8",  nome:"Luiz Fernando dos Santos",   mes:"Janeiro",   data:"21/01/2026", status:"Faltou",    obs:"" },
  { id:"ja9",  nome:"Pedro Paulo Souza",          mes:"Janeiro",   data:"22/01/2026", status:"Faltou",    obs:"" },
  { id:"ja10", nome:"Kilza Cristina Leite Mauch", mes:"Janeiro",   data:"27/01/2026", status:"Pendente",  obs:"" },
  { id:"fa1",  nome:"Willian Gomes",              mes:"Fevereiro", data:"02/04/2026", status:"Aprovado",  obs:"" },
  { id:"fa2",  nome:"Robson Gimenez",             mes:"Fevereiro", data:"05/02/2026", status:"Aprovado",  obs:"" },
  { id:"fa3",  nome:"Magna Oliveira Assis",       mes:"Fevereiro", data:"10/02/2026", status:"Aprovado",  obs:"" },
  { id:"fa4",  nome:"Josuel Dos Santos",          mes:"Fevereiro", data:"18/02/2026", status:"Pendente",  obs:"" },
  { id:"fa5",  nome:"Isabely de Oliveira",        mes:"Fevereiro", data:"19/02/2026", status:"Aprovado",  obs:"" },
  { id:"fa6",  nome:"Francisco Correia",          mes:"Fevereiro", data:"26/02/2026", status:"Aprovado",  obs:"" },
  { id:"fa7",  nome:"Bruno Henrique",             mes:"Fevereiro", data:"26/02/2026", status:"Pendente",  obs:"" },
  { id:"ma1",  nome:"Robinson Aparecido",         mes:"Março",     data:"03/03/2026", status:"Aprovado",  obs:"" },
  { id:"ma2",  nome:"Fatima Lima",                mes:"Março",     data:"03/03/2026", status:"Reprovado", obs:"" },
  { id:"ma3",  nome:"Jael Gomes",                 mes:"Março",     data:"04/03/2026", status:"Faltou",    obs:"" },
  { id:"ma4",  nome:"Elis Regina Souza",          mes:"Março",     data:"10/03/2026", status:"Aprovado",  obs:"" },
  { id:"ma5",  nome:"Diego Arita",                mes:"Março",     data:"10/03/2026", status:"Aprovado",  obs:"" },
  { id:"ma6",  nome:"Ester Aparecida Leonello",   mes:"Março",     data:"16/03/2026", status:"Aprovado",  obs:"" },
  { id:"ma7",  nome:"Daiane Martins",             mes:"Março",     data:"31/03/2026", status:"Pendente",  obs:"" },
  { id:"aa1",  nome:"Vivian Gallego Arruda",      mes:"Abril",     data:"01/04/2026", status:"Aprovado",  obs:"" },
  { id:"aa2",  nome:"Thalisson Guedes",           mes:"Abril",     data:"01/04/2026", status:"Faltou",    obs:"" },
  { id:"aa3",  nome:"Asafe Emanuel Matos Gama",   mes:"Abril",     data:"02/04/2026", status:"Aprovado",  obs:"" },
  { id:"aa4",  nome:"Ivanilda Leite de Souza",    mes:"Abril",     data:"06/04/2026", status:"Aprovado",  obs:"" },
  { id:"aa5",  nome:"Ivanildo Ramos",             mes:"Abril",     data:"08/04/2026", status:"Faltou",    obs:"" },
  { id:"mia1", nome:"Bianca Tainá",               mes:"Maio",      data:"04/05/2026", status:"Follow Up", obs:"" },
  { id:"mia2", nome:"Ines de Souza",              mes:"Maio",      data:"05/05/2026", status:"Faltou",    obs:"" },
  { id:"mia3", nome:"Fabiana Castilho",           mes:"Maio",      data:"06/05/2026", status:"Faltou",    obs:"" },
  { id:"mia4", nome:"Josefa Severina",            mes:"Maio",      data:"07/05/2026", status:"Aprovado",  obs:"" },
  { id:"mia5", nome:"Mariane Souza da Cruz",      mes:"Maio",      data:"13/05/2026", status:"Aprovado",  obs:"" },
  { id:"mia6", nome:"Adrian Ryan de Souza",       mes:"Maio",      data:"13/05/2026", status:"Faltou",    obs:"" },
]
