export const PROCEDIMENTOS = [
  "RestauraÃ§Ãµes","Limpezas","Clareamento","Cirurgias",
  "Implantes","Ortodontia","Invisa","Placas",
  "Lentes Porcelana","Lentes Resina","Endodontia","PrÃ³teses"
]
export const PROC_CFG = [
  { key:"Cirurgias",        icon:"âœ‚ï¸",  color:"#dc2626", bg:"#fef2f2", label:"Cirurgias"        },
  { key:"Implantes",        icon:"ðŸ”©",  color:"#7c3aed", bg:"#f5f3ff", label:"Implantes"        },
  { key:"Ortodontia",       icon:"ðŸ“",  color:"#1d6fd8", bg:"#eff6ff", label:"Ortodontia"       },
  { key:"RestauraÃ§Ãµes",     icon:"ðŸ¦·",  color:"#0d9488", bg:"#f0fdfa", label:"RestauraÃ§Ãµes"     },
  { key:"Limpezas",         icon:"âœ¨",  color:"#16a34a", bg:"#f0fdf4", label:"Limpezas"         },
  { key:"Clareamento",      icon:"âš¡",  color:"#ca8a04", bg:"#fefce8", label:"Clareamento"      },
  { key:"PrÃ³teses",         icon:"ðŸ¦´",  color:"#ea580c", bg:"#fff7ed", label:"PrÃ³teses"         },
  { key:"Endodontia",       icon:"ðŸ©º",  color:"#be185d", bg:"#fdf2f8", label:"Endodontia"       },
  { key:"Lentes Porcelana", icon:"ðŸ’Ž",  color:"#0369a1", bg:"#f0f9ff", label:"Lentes Porcelana" },
  { key:"Lentes Resina",    icon:"ðŸ’Ž",  color:"#4f46e5", bg:"#eef2ff", label:"Lentes Resina"    },
  { key:"Invisa",           icon:"ðŸ‘",  color:"#0891b2", bg:"#ecfeff", label:"Invisalign"       },
  { key:"Placas",           icon:"ðŸ›¡",  color:"#65a30d", bg:"#f7fee7", label:"Placas"           },
]
export const STATUS_AV = ["Aprovado","Faltou","Em Aberto","Follow Up","Reprovado","Pendente"]
export const STATUS_CFG = {
  "Aprovado":  { color:"#16a34a", bg:"#f0fdf4", border:"#bbf7d0" },
  "Faltou":    { color:"#dc2626", bg:"#fef2f2", border:"#fecaca" },
  "Em Aberto": { color:"#7c3aed", bg:"#f5f3ff", border:"#ddd6fe" },
  "Follow Up": { color:"#1d6fd8", bg:"#eff6ff", border:"#bfdbfe" },
  "Reprovado": { color:"#be185d", bg:"#fdf2f8", border:"#fbcfe8" },
  "Pendente":  { color:"#ca8a04", bg:"#fefce8", border:"#fef08a" },
}
export const MESES = ["Janeiro","Fevereiro","MarÃ§o","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"]

export const SEED_PACIENTES = [
  { id:"jap0", nome:"JosÃ© do Lago", mes:"Janeiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap1", nome:"Adriele Cheregati", mes:"Janeiro", procs:{"RestauraÃ§Ãµes":"16"}, feitos:{}, obs:"" },
  { id:"jap2", nome:"Jawad ataya", mes:"Janeiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap3", nome:"Alaa ataya", mes:"Janeiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap4", nome:"Geisy Kelli da Silva", mes:"Janeiro", procs:{"RestauraÃ§Ãµes":"11.12.14.1744.45", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap5", nome:"Liliana AndrÃ©ia GuimarÃ£es", mes:"Janeiro", procs:{"RestauraÃ§Ãµes":"46", "Limpezas":"1", "Clareamento":"Gengivectimia", "Cirurgias":"25", "Ortodontia":"EstÃ©tico", "PrÃ³teses":"Coroa Provisoria"}, feitos:{}, obs:"" },
  { id:"jap6", nome:"Ana Clara Gentil", mes:"Janeiro", procs:{"RestauraÃ§Ãµes":"13.14.24.16", "Limpezas":"1", "Ortodontia":"Estetico"}, feitos:{}, obs:"" },
  { id:"jap7", nome:"Rosa Helena Ferreira", mes:"Janeiro", procs:{"RestauraÃ§Ãµes":"18.28.27.25", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap9", nome:"Rodrigo Benatti Dias", mes:"Janeiro", procs:{"RestauraÃ§Ãµes":"47", "Limpezas":"1", "Cirurgias":"28", "Ortodontia":"Convensional"}, feitos:{}, obs:"" },
  { id:"jap10", nome:"Nathalie Prieto de Morais", mes:"Janeiro", procs:{"RestauraÃ§Ãµes":"11.16.17.12.22", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap11", nome:"Juliana Cristina Gino", mes:"Janeiro", procs:{"RestauraÃ§Ãµes":"14", "Limpezas":"1", "Cirurgias":"28.38"}, feitos:{}, obs:"" },
  { id:"jap12", nome:"Kevin Rian Fernandes", mes:"Janeiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap13", nome:"Itamar Soler Martins", mes:"Janeiro", procs:{"RestauraÃ§Ãµes":"26.17.", "Limpezas":"1", "Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"jap14", nome:"Livia Maria de Oliveira", mes:"Janeiro", procs:{"Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"jap15", nome:"Jozenilda dos Santos", mes:"Janeiro", procs:{}, feitos:{}, obs:"" },
  { id:"jap16", nome:"Eduardo AntÃ´nio Ferrari", mes:"Janeiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap17", nome:"Carlos Eduardo MÃ³dena", mes:"Janeiro", procs:{"RestauraÃ§Ãµes":"17.35", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep0", nome:"Paciente", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"RestauraÃ§Ãµes", "Limpezas":"Limpezas", "Clareamento":"Clareamento", "Cirurgias":"Cirurgias", "Implantes":"Implantes", "Ortodontia":"Ortodontia", "Invisa":"Invisa", "Placas":"Placas", "Lentes Porcelana":"Lentes Porcelana", "Lentes Resina":"Lentes Resina", "Endodontia":"Endodontia", "PrÃ³teses":"Proteses"}, feitos:{}, obs:"" },
  { id:"fep1", nome:"Taina de Campos", mes:"Fevereiro", procs:{"Lentes Resina":"11.21"}, feitos:{}, obs:"" },
  { id:"fep2", nome:"Willian Gomes", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"21.11.16.46", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep3", nome:"Henrique do Carmo", mes:"Fevereiro", procs:{"Lentes Porcelana":"25"}, feitos:{}, obs:"" },
  { id:"fep4", nome:"AndrÃ© Mariano", mes:"Fevereiro", procs:{"Limpezas":"1", "Lentes Resina":"23"}, feitos:{}, obs:"" },
  { id:"fep5", nome:"Bernardo Bergamin", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"75", "Limpezas":"1", "Ortodontia":"Ortopedico"}, feitos:{}, obs:"" },
  { id:"fep6", nome:"Magna Oliveira", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"23", "Endodontia":"23"}, feitos:{}, obs:"" },
  { id:"fep7", nome:"Bruno Eduardo Vieira", mes:"Fevereiro", procs:{"Limpezas":"1", "Ortodontia":"ContenÃ§Ã£o"}, feitos:{}, obs:"" },
  { id:"fep8", nome:"Maycon da Silva Barofe", mes:"Fevereiro", procs:{}, feitos:{}, obs:"" },
  { id:"fep9", nome:"Arthur Ernandes", mes:"Fevereiro", procs:{"Ortodontia":"Ortopedico"}, feitos:{}, obs:"" },
  { id:"fep10", nome:"Giovana AngÃ©lica Borin", mes:"Fevereiro", procs:{}, feitos:{}, obs:"" },
  { id:"fep11", nome:"Adriano Furigo", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"21", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep12", nome:"Rosemary da Silva Teodoro", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"46", "Limpezas":"1", "Lentes Resina":"11.21"}, feitos:{}, obs:"" },
  { id:"fep13", nome:"Evelin Lusa", mes:"Fevereiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep14", nome:"Gabriel Pires da Silva", mes:"Fevereiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep15", nome:"Beatriz Machado", mes:"Fevereiro", procs:{"Limpezas":"1", "Ortodontia":"ContenÃ§Ã£o"}, feitos:{}, obs:"" },
  { id:"fep16", nome:"Lyandra Santos Alves", mes:"Fevereiro", procs:{"Limpezas":"1", "Ortodontia":"ContenÃ§Ã£o"}, feitos:{}, obs:"" },
  { id:"fep17", nome:"Luma Barbara", mes:"Fevereiro", procs:{"Invisa":"ContenÃ§Ã£o"}, feitos:{}, obs:"" },
  { id:"fep18", nome:"Nathalia Bruna", mes:"Fevereiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep19", nome:"Josiane Cristina", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"26.22.11", "Limpezas":"1", "Endodontia":"18"}, feitos:{}, obs:"" },
  { id:"fep20", nome:"Cicelio do Nascimento", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"12.21.47.", "Limpezas":"2", "Clareamento":"1", "Cirurgias":"Por elemento", "Implantes":"45", "Lentes Resina":"11", "Endodontia":"35", "PrÃ³teses":"35"}, feitos:{}, obs:"" },
  { id:"fep21", nome:"Josuel dos Santos", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"45.21", "Limpezas":"3"}, feitos:{}, obs:"" },
  { id:"fep22", nome:"Isabelly de Oliveira", mes:"Fevereiro", procs:{"Cirurgias":"48.28"}, feitos:{}, obs:"" },
  { id:"fep23", nome:"Lenita A. Scomparin", mes:"Fevereiro", procs:{"Implantes":"1"}, feitos:{}, obs:"" },
  { id:"fep24", nome:"Amanda Godoi", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"36", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep25", nome:"Pedro Scomparin", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"17.26.27.", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep26", nome:"Maicon Rafael", mes:"Fevereiro", procs:{"Limpezas":"1", "Invisa":"ContenÃ§Ã£o"}, feitos:{}, obs:"" },
  { id:"fep27", nome:"Rubens Moreira", mes:"Fevereiro", procs:{"PrÃ³teses":"22"}, feitos:{}, obs:"" },
  { id:"fep28", nome:"Robson Gimenez", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"34.35.23.24.25.14.15.44.45.16.28.11.12.21.22", "Limpezas":"1", "Cirurgias":"46.27", "Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"fep29", nome:"Karina Martins", mes:"Fevereiro", procs:{"Lentes Porcelana":"31.32.33.34.35.41.42.43.44.45"}, feitos:{}, obs:"" },
  { id:"fep30", nome:"Anderson Pereira", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"43.44.34.37.46.", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep31", nome:"Francisco Correa", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"21.27.46", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep32", nome:"Bruno Henrique", mes:"Fevereiro", procs:{"RestauraÃ§Ãµes":"13.44.46.35.27.17", "Limpezas":"1", "Cirurgias":"38.48"}, feitos:{}, obs:"" },
  { id:"fep33", nome:"JosÃ© Carlos Moreira", mes:"Fevereiro", procs:{"Cirurgias":"Tracionamento 23"}, feitos:{}, obs:"" },
  { id:"fep34", nome:"Robson Beserra", mes:"Fevereiro", procs:{"Invisa":"ContenÃ§Ã£o inf"}, feitos:{}, obs:"" },
  { id:"map0", nome:"Robinson Aparecido da Silva", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"11.21.26.36.31", "Limpezas":"1", "Cirurgias":"18.28.38.48", "Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"map1", nome:"SÃ©rgio Luis da Silva", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"26.16.", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"map2", nome:"Giovana AngÃ©lica Borin", mes:"MarÃ§o", procs:{}, feitos:{}, obs:"" },
  { id:"map3", nome:"Simone Aparecida Secolin", mes:"MarÃ§o", procs:{}, feitos:{}, obs:"" },
  { id:"map4", nome:"Jean Moacir Casaril", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"36.26.17", "Limpezas":"1", "Lentes Resina":"13"}, feitos:{}, obs:"" },
  { id:"map5", nome:"Malak Badredeen", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"46.17"}, feitos:{}, obs:"" },
  { id:"map6", nome:"Beatriz Sales de Souza", mes:"MarÃ§o", procs:{}, feitos:{}, obs:"" },
  { id:"map7", nome:"Elis Regina Sousa", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"11.14.16.45..26,34.35.36.46", "Limpezas":"1", "Cirurgias":"18.28.38", "Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"map8", nome:"Rafaela Amaro de Carvalho", mes:"MarÃ§o", procs:{}, feitos:{}, obs:"" },
  { id:"map9", nome:"Joao Fernando Pangalde", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"12.13.21", "Limpezas":"1", "Cirurgias":"exo"}, feitos:{}, obs:"" },
  { id:"map10", nome:"Polyanna Barsotini Romanini", mes:"MarÃ§o", procs:{}, feitos:{}, obs:"" },
  { id:"map11", nome:"Edna Ferreira de Mello", mes:"MarÃ§o", procs:{}, feitos:{}, obs:"" },
  { id:"map12", nome:"Ana LÃ­via Faria da Silva", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"46.47.21.36.37.26", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"map13", nome:"Ester Aparecida Leonello", mes:"MarÃ§o", procs:{}, feitos:{}, obs:"" },
  { id:"map14", nome:"Josuel dos Santos Dias", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"43", "Endodontia":"43"}, feitos:{}, obs:"" },
  { id:"map15", nome:"Pietro Niller Mello", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"23", "Limpezas":"1", "Invisa":"lite"}, feitos:{}, obs:"" },
  { id:"map16", nome:"Diego Arita", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"46.15.37", "Limpezas":"1", "Cirurgias":"aumento de coroa"}, feitos:{}, obs:"" },
  { id:"map17", nome:"Maria JÃºlia Queiroz Bassetto", mes:"MarÃ§o", procs:{"Ortodontia":"ManutenÃ§Ã£o"}, feitos:{}, obs:"" },
  { id:"map18", nome:"Beatriz Machado", mes:"MarÃ§o", procs:{}, feitos:{}, obs:"" },
  { id:"map19", nome:"JosÃ© Aparecido Balanciele", mes:"MarÃ§o", procs:{"PrÃ³teses":"Total"}, feitos:{}, obs:"" },
  { id:"map20", nome:"Suely Francisca S. Marineri", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"25.37.", "Limpezas":"1", "Cirurgias":"35"}, feitos:{}, obs:"" },
  { id:"map21", nome:"Eduardo AntÃ´nio Ferrari", mes:"MarÃ§o", procs:{"Limpezas":"1", "Cirurgias":"14", "Invisa":"Comprehensive", "PrÃ³teses":"Coroa Prov"}, feitos:{}, obs:"" },
  { id:"map22", nome:"Diego Arita", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"46.15.37", "Limpezas":"1", "Cirurgias":"Aumento coroa 37"}, feitos:{}, obs:"" },
  { id:"map23", nome:"Rafaela Amaro de Carvalho", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"25", "Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"map24", nome:"Liliana AndrÃ©ia GuimarÃ£es", mes:"MarÃ§o", procs:{"Clareamento":"Caseiro/consultÃ³rio"}, feitos:{}, obs:"" },
  { id:"map25", nome:"CÃ¡tia GonÃ§alves Cabral", mes:"MarÃ§o", procs:{"Limpezas":"1", "Lentes Resina":"15"}, feitos:{}, obs:"" },
  { id:"map26", nome:"Anderson Jesus Batista", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"26.17.11.22.24..24", "Limpezas":"1", "PrÃ³teses":"Coroa 16"}, feitos:{}, obs:"" },
  { id:"map27", nome:"Thais Soares de Lucema", mes:"MarÃ§o", procs:{"Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"map28", nome:"Lucia Moraes Porto", mes:"MarÃ§o", procs:{}, feitos:{}, obs:"" },
  { id:"map29", nome:"Roselena PatrÃ­cia Arantes", mes:"MarÃ§o", procs:{}, feitos:{}, obs:"" },
  { id:"map30", nome:"Weber Rodolfo Lopes", mes:"MarÃ§o", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"map31", nome:"Lucas Natan Mendes", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"17.27.35.11.21", "Limpezas":"1", "Cirurgias":"18.28.38.48", "Lentes Resina":"13.14.15.11.12.13."}, feitos:{}, obs:"" },
  { id:"map32", nome:"Thais Soares de Lucema", mes:"MarÃ§o", procs:{"Ortodontia":"Convencional", "Lentes Resina":"21.22.23.24.25"}, feitos:{}, obs:"" },
  { id:"map33", nome:"Andressa Cardoso", mes:"MarÃ§o", procs:{"RestauraÃ§Ãµes":"46.47"}, feitos:{}, obs:"" },
  { id:"map34", nome:"karina Teobaldo", mes:"MarÃ§o", procs:{"Ortodontia":"ontenÃ§Ã£o"}, feitos:{}, obs:"" },
  { id:"abp0", nome:"Vivian Gallego Arruda", mes:"Abril", procs:{"Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"abp1", nome:"SÃ©rgio Luis da Silva", mes:"Abril", procs:{"RestauraÃ§Ãµes":"26.16", "Limpezas":"1", "Invisa":"Lite"}, feitos:{}, obs:"" },
  { id:"abp2", nome:"Asafe Emanuel Matos Gama", mes:"Abril", procs:{"RestauraÃ§Ãµes":"46.47.27", "Limpezas":"1", "Ortodontia":"EstÃ©tico"}, feitos:{}, obs:"" },
  { id:"abp3", nome:"Ivanilda Leite de Souza Lima", mes:"Abril", procs:{"RestauraÃ§Ãµes":"45.25.26", "Limpezas":"1", "Clareamento":"1"}, feitos:{}, obs:"" },
  { id:"abp4", nome:"Leyla Cristina de Toledo", mes:"Abril", procs:{"RestauraÃ§Ãµes":"45.16"}, feitos:{}, obs:"" },
  { id:"abp5", nome:"Yasmin da Silva Noch", mes:"Abril", procs:{"RestauraÃ§Ãµes":"36.26.16", "Ortodontia":"ContenÃ§Ã£o inf"}, feitos:{}, obs:"" },
  { id:"abp6", nome:"Elane Cristina Cardoso", mes:"Abril", procs:{"Lentes Resina":"Dente13"}, feitos:{}, obs:"" },
  { id:"abp7", nome:"Clara Rodrigues", mes:"Abril", procs:{"Ortodontia":"ManutenÃ§Ã£o"}, feitos:{}, obs:"" },
  { id:"abp8", nome:"Luiza Odete Agostinho", mes:"Abril", procs:{"RestauraÃ§Ãµes":"21.37", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"abp9", nome:"Gislene Freitas de camargo", mes:"Abril", procs:{"RestauraÃ§Ãµes":"11.15.24.25", "Limpezas":"1", "Ortodontia":"EstÃ©ticio", "Endodontia":"25"}, feitos:{}, obs:"" },
  { id:"abp10", nome:"Izaias Moraes da Silva", mes:"Abril", procs:{"RestauraÃ§Ãµes":"36.337.47", "Limpezas":"1", "Clareamento":"1"}, feitos:{}, obs:"" },
  { id:"abp11", nome:"Jofran Santa Rosa Cruz", mes:"Abril", procs:{"RestauraÃ§Ãµes":"25", "Limpezas":"1", "Endodontia":"25"}, feitos:{}, obs:"" },
  { id:"abp12", nome:"Heytor dos Santos Xavier", mes:"Abril", procs:{"Ortodontia":"Ortopedico"}, feitos:{}, obs:"" },
  { id:"abp13", nome:"Jael Gomes Haine", mes:"Abril", procs:{"RestauraÃ§Ãµes":"16.37", "Limpezas":"1", "Cirurgias":"46.36"}, feitos:{}, obs:"" },
  { id:"abp14", nome:"Rosana Aparecida Lima", mes:"Abril", procs:{"RestauraÃ§Ãµes":"34", "Cirurgias":"34"}, feitos:{}, obs:"" },
  { id:"abp15", nome:"Laura Ernst Pitta", mes:"Abril", procs:{"RestauraÃ§Ãµes":"21"}, feitos:{}, obs:"" },
  { id:"abp16", nome:"Mylena Cristina Borges", mes:"Abril", procs:{"RestauraÃ§Ãµes":"35.36"}, feitos:{}, obs:"" },
  { id:"abp17", nome:"Adriano Pires Neto", mes:"Abril", procs:{"RestauraÃ§Ãµes":"12..14.47"}, feitos:{}, obs:"" },
  { id:"abp18", nome:"Vanessa de Souza Lima", mes:"Abril", procs:{"RestauraÃ§Ãµes":"15", "Limpezas":"1", "Cirurgias":"18.28.48"}, feitos:{}, obs:"" },
  { id:"abp19", nome:"Maria de Lourdes Carvalho", mes:"Abril", procs:{"RestauraÃ§Ãµes":"13.14.15.23.24.34.35.3645.44", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"abp20", nome:"Liliane Lima de Morais", mes:"Abril", procs:{"Limpezas":"1", "Lentes Resina":"11.21.22"}, feitos:{}, obs:"" },
  { id:"abp21", nome:"Matheus Barbosa da Silva", mes:"Abril", procs:{"Limpezas":"1", "Ortodontia":"ContenÃ§Ã£o"}, feitos:{}, obs:"" },
  { id:"abp22", nome:"Lucas Barbosa da Silva", mes:"Abril", procs:{"Limpezas":"1", "Ortodontia":"ContenÃ§Ã£o"}, feitos:{}, obs:"" },
  { id:"abp23", nome:"Carlos Joaquim Souza", mes:"Abril", procs:{"Ortodontia":"Ortopedico"}, feitos:{}, obs:"" },
  { id:"abp24", nome:"Kamile da Silva Persego", mes:"Abril", procs:{"RestauraÃ§Ãµes":"16.17.36", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"abp25", nome:"Mayara Ferreira Marques", mes:"Abril", procs:{"RestauraÃ§Ãµes":"11.21.17.24.", "Limpezas":"1", "Cirurgias":"18.38.48", "Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"abp26", nome:"JoÃ£o Carlos Elias de Campo", mes:"Abril", procs:{"RestauraÃ§Ãµes":"14.15.16.36.45", "Limpezas":"1", "Implantes":"21", "Endodontia":"23", "PrÃ³teses":"21 Coroa"}, feitos:{}, obs:"" },
  { id:"abp27", nome:"Luis Afonso Zorzetto Laurindo", mes:"Abril", procs:{"RestauraÃ§Ãµes":"14.15.35.3624.25.47", "Cirurgias":"28", "Invisa":"Lite"}, feitos:{}, obs:"" },
  { id:"abp28", nome:"Miria Aparecida Zorzetto", mes:"Abril", procs:{"RestauraÃ§Ãµes":"37", "Limpezas":"1", "PrÃ³teses":"12 emax"}, feitos:{}, obs:"" },
  { id:"abp29", nome:"PÃ¢mella Maciel Rodrigues", mes:"Abril", procs:{"RestauraÃ§Ãµes":"16.17.27.36.37.47", "Limpezas":"1", "Cirurgias":"26", "Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"abp30", nome:"AndrÃ© Luiz Gozzi Joaquim", mes:"Abril", procs:{"Implantes":"21.23"}, feitos:{}, obs:"" },
  { id:"abp31", nome:"AndrÃ© Luiz Gozzi Joaquim", mes:"Abril", procs:{"Cirurgias":"Enxerto"}, feitos:{}, obs:"" },
  { id:"abp32", nome:"Vitor Hugo Rodrigues", mes:"Abril", procs:{"RestauraÃ§Ãµes":"26", "Endodontia":"26"}, feitos:{}, obs:"" },
  { id:"abp33", nome:"Adriana Ueda de Oliveira", mes:"Abril", procs:{"Invisa":"ContenÃ§Ã£o"}, feitos:{}, obs:"" },
  { id:"abp34", nome:"Geraldo Ferreira", mes:"Abril", procs:{"PrÃ³teses":"36 emax"}, feitos:{}, obs:"" },
  { id:"abp35", nome:"Maria Eugenia Martinho", mes:"Abril", procs:{"RestauraÃ§Ãµes":"32.31.33.13.21.23.41", "Cirurgias":"27.15", "PrÃ³teses":"Ppr"}, feitos:{}, obs:"" },
  { id:"abp36", nome:"Regiany Lucy Rodrigues", mes:"Abril", procs:{"RestauraÃ§Ãµes":"35.43", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"abp37", nome:"Paulo JosÃ© Franco", mes:"Abril", procs:{"Implantes":"12.15", "PrÃ³teses":"11.12.13.14.15.21.22.  grampo"}, feitos:{}, obs:"" },
  { id:"abp38", nome:"Thiago AraÃºjo", mes:"Abril", procs:{"Limpezas":"1", "Implantes":"46.26.", "Lentes Resina":"11.12.13.14.16.21.22.23.24."}, feitos:{}, obs:"" },
  { id:"abp39", nome:"Liliana AndrÃ©ia GuimarÃ£es", mes:"Abril", procs:{"Limpezas":"1", "PrÃ³teses":"Coroa Provisoria dente 25"}, feitos:{}, obs:"" },
  { id:"abp40", nome:"Ana Lidia Alves da AnunciaÃ§Ã£o", mes:"Abril", procs:{"RestauraÃ§Ãµes":"11.21.23.24.25.27", "Limpezas":"1", "Cirurgias":"48.18.38.", "Ortodontia":"Convencional", "PrÃ³teses":"36 emax"}, feitos:{}, obs:"" },
  { id:"abp41", nome:"Angelo Emilio de Toledo", mes:"Abril", procs:{"Limpezas":"1", "PrÃ³teses":"ajuste implante"}, feitos:{}, obs:"" },
  { id:"abp42", nome:"InÃªs Ferreira de Lima", mes:"Abril", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"map0", nome:"Felipe de Castro Silveira", mes:"Maio", procs:{"Ortodontia":"Ortopedico"}, feitos:{}, obs:"" },
  { id:"map1", nome:"Diego Arita", mes:"Maio", procs:{}, feitos:{}, obs:"" },
  { id:"map2", nome:"Iolanda Ap. GonÃ§alves", mes:"Maio", procs:{"Lentes Resina":"17", "PrÃ³teses":"Coroa emax 46"}, feitos:{}, obs:"" },
  { id:"map3", nome:"Elizabethe de Melo", mes:"Maio", procs:{"PrÃ³teses":"Coroa 11"}, feitos:{}, obs:"" },
  { id:"map4", nome:"Ana Laura Borin", mes:"Maio", procs:{"Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"map5", nome:"Aparecida Penha", mes:"Maio", procs:{}, feitos:{}, obs:"" },
  { id:"map6", nome:"Josefa severina Torres", mes:"Maio", procs:{"Limpezas":"1", "Clareamento":"1", "Cirurgias":"46", "Ortodontia":"ContenÃ§Ã£o"}, feitos:{}, obs:"" },
  { id:"map7", nome:"Charles Kelvin Paulino", mes:"Maio", procs:{"RestauraÃ§Ãµes":"14", "Endodontia":"14"}, feitos:{}, obs:"" },
  { id:"map8", nome:"Lenita A. Scomparin", mes:"Maio", procs:{}, feitos:{}, obs:"" },
  { id:"map9", nome:"JosÃ© Carlos Blefari", mes:"Maio", procs:{}, feitos:{}, obs:"" },
  { id:"map10", nome:"Lucas Roberto", mes:"Maio", procs:{"RestauraÃ§Ãµes":"15.16.24.34.44.35", "Limpezas":"1", "Ortodontia":"Auto Ligado", "PrÃ³teses":"Coroa Prov 37"}, feitos:{}, obs:"" },
  { id:"map11", nome:"JosÃ© Antonio Scomparin", mes:"Maio", procs:{}, feitos:{}, obs:"" },
  { id:"map12", nome:"Gabriel Pires da Silva", mes:"Maio", procs:{}, feitos:{}, obs:"" },
  { id:"map13", nome:"Celso Benatti", mes:"Maio", procs:{"Endodontia":"34", "PrÃ³teses":"Coroa emax 34"}, feitos:{}, obs:"" },
  { id:"map14", nome:"Liliana AndrÃ©ia GuimarÃ£es", mes:"Maio", procs:{"PrÃ³teses":"Coroa 25"}, feitos:{}, obs:"" },
  { id:"map15", nome:"Mariane souza da cruz", mes:"Maio", procs:{"RestauraÃ§Ãµes":"16.17.36.37", "Limpezas":"1", "Clareamento":"Inferior", "Cirurgias":"Gengicevtomia", "Lentes Resina":"11.12.13.14.15.21.22.23.24.25"}, feitos:{}, obs:"" },
  { id:"map16", nome:"Denise Porto Pieroni", mes:"Maio", procs:{"PrÃ³teses":"Coroa 25.46."}, feitos:{}, obs:"" },
  { id:"map17", nome:"InÃªs Ferreira de Lima", mes:"Maio", procs:{"RestauraÃ§Ãµes":"13.31.35.41.46."}, feitos:{}, obs:"" },
  { id:"map18", nome:"Gabriella Christina Miguel", mes:"Maio", procs:{"Limpezas":"1", "Ortodontia":"Invisa"}, feitos:{}, obs:"" },
]

export const SEED_AVALIACOES = [
  { id:"jaa0", nome:"Maycon da Silva Barofe", mes:"Janeiro", data:"14/01/2026", status:"Pendente", obs:"" },
  { id:"jaa1", nome:"Rosa Helena Ferreira de", mes:"Janeiro", data:"14/01/2026", status:"Aprovado", obs:"" },
  { id:"jaa2", nome:"Gabriel Rossi", mes:"Janeiro", data:"14/01/2026", status:"Faltou", obs:"" },
  { id:"jaa3", nome:"Liliana AndrÃ©ia GuimarÃ£es", mes:"Janeiro", data:"15/01/2025", status:"Aprovado", obs:"" },
  { id:"jaa4", nome:"Adriele Cheregati Fernandes", mes:"Janeiro", data:"15/01/2025", status:"Aprovado", obs:"" },
  { id:"jaa5", nome:"Geisy Kelli da Silva", mes:"Janeiro", data:"15/01/2026", status:"Aprovado", obs:"" },
  { id:"jaa6", nome:"Ana Clara Gentil", mes:"Janeiro", data:"15/01/2026", status:"Aprovado", obs:"" },
  { id:"jaa7", nome:"Itamar Soler", mes:"Janeiro", data:"20/01/2026", status:"Aprovado", obs:"" },
  { id:"jaa8", nome:"Luiz Fernando dos Santos", mes:"Janeiro", data:"21/01/2026", status:"Faltou", obs:"" },
  { id:"jaa9", nome:"Maria CecÃ­lia Ozanique", mes:"Janeiro", data:"22/01/2026", status:"Pendente", obs:"" },
  { id:"jaa10", nome:"Pedro Paulo Souza", mes:"Janeiro", data:"22/01/2026", status:"Faltou", obs:"" },
  { id:"jaa11", nome:"Livia Maria de Oliveira", mes:"Janeiro", data:"22/01/2026", status:"Aprovado", obs:"" },
  { id:"jaa12", nome:"Nathalie Prieto de Morais", mes:"Janeiro", data:"22/01/2026", status:"Aprovado", obs:"" },
  { id:"jaa13", nome:"Kilza Cristina Leite Mauch", mes:"Janeiro", data:"27/01/2026", status:"Pendente", obs:"" },
  { id:"fea0", nome:"Willian Gomes", mes:"Fevereiro", data:"02/04/2026", status:"Aprovado", obs:"" },
  { id:"fea1", nome:"Claudinei dos Santos", mes:"Fevereiro", data:"02/04/2026", status:"Pendente", obs:"" },
  { id:"fea2", nome:"Regina Celia Coser", mes:"Fevereiro", data:"02/05/2026", status:"Pendente", obs:"" },
  { id:"fea3", nome:"RobsonGimenez", mes:"Fevereiro", data:"02/05/2026", status:"Aprovado", obs:"" },
  { id:"fea4", nome:"Magna Oliveira Assis", mes:"Fevereiro", data:"02/10/2026", status:"Aprovado", obs:"" },
  { id:"fea5", nome:"Pedro T Neto", mes:"Fevereiro", data:"02/10/2026", status:"Pendente", obs:"" },
  { id:"fea6", nome:"Rafael Cesar da Mata", mes:"Fevereiro", data:"02/11/2026", status:"Pendente", obs:"" },
  { id:"fea7", nome:"Rosemery da Silva", mes:"Fevereiro", data:"02/11/2026", status:"Aprovado", obs:"" },
  { id:"fea8", nome:"JosÃ© carlos Semolini", mes:"Fevereiro", data:"02/12/2026", status:"Pendente", obs:"" },
  { id:"fea9", nome:"Josuel Dos Santos", mes:"Fevereiro", data:"18/02/2026", status:"Pendente", obs:"" },
  { id:"fea10", nome:"Enrico Oliveira", mes:"Fevereiro", data:"19/02/2026", status:"Pendente", obs:"" },
  { id:"fea11", nome:"Isabely de Oliveira", mes:"Fevereiro", data:"19/02/2026", status:"Aprovado", obs:"" },
  { id:"fea12", nome:"Amanda Godoi", mes:"Fevereiro", data:"19/02/2026", status:"Pendente", obs:"" },
  { id:"fea13", nome:"Joao Fernando", mes:"Fevereiro", data:"19/02/2026", status:"Aprovado", obs:"" },
  { id:"fea14", nome:"Francisco Correia", mes:"Fevereiro", data:"26/02/2026", status:"Aprovado", obs:"" },
  { id:"fea15", nome:"Bruno Henrique", mes:"Fevereiro", data:"26/02/2026", status:"Pendente", obs:"" },
  { id:"fea16", nome:"Robson Beserra", mes:"Fevereiro", data:"26/02/2026", status:"Pendente", obs:"" },
  { id:"fea17", nome:"Julia  Rafhaela", mes:"Fevereiro", data:"26/02/2026", status:"Pendente", obs:"" },
  { id:"maa0", nome:"Mileny Silvana", mes:"MarÃ§o", data:"03/02/2026", status:"Pendente", obs:"" },
  { id:"maa1", nome:"Robinson Aparecido", mes:"MarÃ§o", data:"03/03/2026", status:"Aprovado", obs:"" },
  { id:"maa2", nome:"Sergio Luiz da Silva", mes:"MarÃ§o", data:"03/03/2026", status:"Pendente", obs:"" },
  { id:"maa3", nome:"Fatima Lima", mes:"MarÃ§o", data:"03/03/2026", status:"Reprovado", obs:"" },
  { id:"maa4", nome:"Jean Moacir", mes:"MarÃ§o", data:"03/03/2026", status:"Aprovado", obs:"" },
  { id:"maa5", nome:"Jael Gomes", mes:"MarÃ§o", data:"03/04/2026", status:"Faltou", obs:"" },
  { id:"maa6", nome:"Neide de Oliveira", mes:"MarÃ§o", data:"03/05/2026", status:"Faltou", obs:"" },
  { id:"maa7", nome:"Elis Regina Souza", mes:"MarÃ§o", data:"03/10/2026", status:"Aprovado", obs:"" },
  { id:"maa8", nome:"Diego Ariate", mes:"MarÃ§o", data:"03/10/2026", status:"Aprovado", obs:"" },
  { id:"maa9", nome:"Ester Aparecida Leonello", mes:"MarÃ§o", data:"16/03", status:"Aprovado", obs:"" },
  { id:"maa10", nome:"Pietro Niller Mello de Campos", mes:"MarÃ§o", data:"16/03", status:"Aprovado", obs:"" },
  { id:"maa11", nome:"CÃ¡tia GonÃ§alves Cabral", mes:"MarÃ§o", data:"â€”", status:"Aprovado", obs:"" },
  { id:"maa12", nome:"JosÃ© Aparecido Balanciele", mes:"MarÃ§o", data:"â€”", status:"Aprovado", obs:"" },
  { id:"maa13", nome:"Guilherme Augusto GregÃ³rio", mes:"MarÃ§o", data:"â€”", status:"Pendente", obs:"" },
  { id:"maa14", nome:"Carlos Joaquim Souza Peixoto", mes:"MarÃ§o", data:"24/04/2026", status:"Pendente", obs:"" },
  { id:"maa15", nome:"Gabriel Joshua Zacarioto", mes:"MarÃ§o", data:"25/04/2026", status:"Pendente", obs:"" },
  { id:"maa16", nome:"Weber Rodolfo Lopes", mes:"MarÃ§o", data:"â€”", status:"Pendente", obs:"" },
  { id:"maa17", nome:"Daiane Martins", mes:"MarÃ§o", data:"31/03/2026", status:"Pendente", obs:"" },
  { id:"maa18", nome:"Maria Clara Martins Ferreira", mes:"MarÃ§o", data:"31/03/2026", status:"Pendente", obs:"" },
  { id:"maa19", nome:"Silvio Candido da Silvia Junior", mes:"MarÃ§o", data:"31/03/2026", status:"Pendente", obs:"" },
  { id:"aba0", nome:"Vivian Gallego Arruda", mes:"Abril", data:"04/01/2026", status:"Aprovado", obs:"" },
  { id:"aba1", nome:"Jhony GuimarÃ£es Evangelista", mes:"Abril", data:"04/01/2026", status:"Pendente", obs:"" },
  { id:"aba2", nome:"Thalisson Guedes", mes:"Abril", data:"04/01/2026", status:"Faltou", obs:"" },
  { id:"aba3", nome:"Caio lucn delfino", mes:"Abril", data:"04/02/2026", status:"Faltou", obs:"" },
  { id:"aba4", nome:"Ana Paula delfino", mes:"Abril", data:"04/02/2026", status:"Faltou", obs:"" },
  { id:"aba5", nome:"Asafe Emanuel Matos Gama", mes:"Abril", data:"04/02/2026", status:"Aprovado", obs:"" },
  { id:"aba6", nome:"Lucas Roberto da silva", mes:"Abril", data:"04/02/2026", status:"Pendente", obs:"" },
  { id:"aba7", nome:"Ivanilda Leite de Souza Lima", mes:"Abril", data:"04/06/2026", status:"Aprovado", obs:"" },
  { id:"aba8", nome:"Liliane lima de morais e Silva", mes:"Abril", data:"04/06/2026", status:"Pendente", obs:"" },
  { id:"aba9", nome:"MichelÃ¢ngelo Dalaqua arruda", mes:"Abril", data:"04/06/2026", status:"Pendente", obs:"" },
  { id:"aba10", nome:"Matheus Gallego arruda", mes:"Abril", data:"04/06/2026", status:"Pendente", obs:"" },
  { id:"aba11", nome:"Luiza Odete Agostinho da Silva", mes:"Abril", data:"04/07/2026", status:"Aprovado", obs:"" },
  { id:"aba12", nome:"Vanessa de Souza Lima", mes:"Abril", data:"04/04/2026", status:"Pendente", obs:"" },
  { id:"aba13", nome:"Ivanildo Ramos", mes:"Abril", data:"04/08/2026", status:"Faltou", obs:"" },
  { id:"aba14", nome:"Livia Ramos", mes:"Abril", data:"04/08/2026", status:"Faltou", obs:"" },
  { id:"aba15", nome:"Gabriel Bella", mes:"Abril", data:"04/08/2026", status:"Em Aberto", obs:"" },
  { id:"aba16", nome:"Maria Eugenia Martinho", mes:"Abril", data:"04/08/2026", status:"Pendente", obs:"" },
  { id:"aba17", nome:"Marcelo Teixeira da Silva", mes:"Abril", data:"04/08/2026", status:"Pendente", obs:"" },
  { id:"aba18", nome:"Isabel dos Santos Henrique", mes:"Abril", data:"04/08/2026", status:"Pendente", obs:"" },
  { id:"aba19", nome:"Silvia Regina Rolla Carneiro", mes:"Abril", data:"04/08/2026", status:"Pendente", obs:"" },
  { id:"aba20", nome:"Miria Aparecida Zorzetto", mes:"Abril", data:"04/08/2026", status:"Aprovado", obs:"" },
  { id:"aba21", nome:"Gislene Freitas de camargo", mes:"Abril", data:"04/09/2026", status:"Aprovado", obs:"" },
  { id:"aba22", nome:"Izaias Moraes da Silva", mes:"Abril", data:"04/09/2026", status:"Aprovado", obs:"" },
  { id:"aba23", nome:"Lilian Damaceno", mes:"Abril", data:"13/04/2026", status:"Pendente", obs:"" },
  { id:"aba24", nome:"Jael Gomes Haine", mes:"Abril", data:"14/04/2026", status:"Aprovado", obs:"" },
  { id:"aba25", nome:"PÃ¢mella Maciel Rodrigues", mes:"Abril", data:"14/04/2026", status:"Aprovado", obs:"" },
  { id:"aba26", nome:"Ivone Mario Alvarenga", mes:"Abril", data:"14/04/2026", status:"Faltou", obs:"" },
  { id:"aba27", nome:"Zilda Aparecida FÃ¡tima Moraes", mes:"Abril", data:"14/04/2026", status:"Faltou", obs:"" },
  { id:"aba28", nome:"Caique Silverio Dourado", mes:"Abril", data:"14/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba29", nome:"Caio Ichiro Arita", mes:"Abril", data:"14/04/2026", status:"Pendente", obs:"" },
  { id:"aba30", nome:"ValquÃ­ria Esteves Nogueira", mes:"Abril", data:"15/04/2026", status:"Pendente", obs:"" },
  { id:"aba31", nome:"Suelen DionÃ­sio de Souza", mes:"Abril", data:"15/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba32", nome:"Ednei Azevedo de Souza", mes:"Abril", data:"15/04/2026", status:"Pendente", obs:"" },
  { id:"aba33", nome:"Maria de Lourdes Carvalho", mes:"Abril", data:"16/04/2026", status:"Pendente", obs:"" },
  { id:"aba34", nome:"Aparecida de FÃ¡tima", mes:"Abril", data:"16/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba35", nome:"Luzia de CÃ¡ssia Fernandes", mes:"Abril", data:"16/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba36", nome:"Liliane Lima de Morais e Silva", mes:"Abril", data:"16/04/2026", status:"Aprovado", obs:"" },
  { id:"aba37", nome:"Regiany Lucy Rodrigues", mes:"Abril", data:"16/04/2026", status:"Aprovado", obs:"" },
  { id:"aba38", nome:"Carolina Cassia Pereira", mes:"Abril", data:"17/04/2026", status:"Pendente", obs:"" },
  { id:"aba39", nome:"JoÃ£o Paulo", mes:"Abril", data:"17/04/2026", status:"Faltou", obs:"" },
  { id:"aba40", nome:"JoÃ£o Carlos Elias de Campo", mes:"Abril", data:"17/04/2026", status:"Pendente", obs:"" },
  { id:"aba41", nome:"Ruan Ferreira de Souza", mes:"Abril", data:"17/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba42", nome:"Daiana Andrade conceiÃ§Ã£o", mes:"Abril", data:"17/04/2026", status:"Faltou", obs:"" },
  { id:"aba43", nome:"Luzia bisotto de Carvalho", mes:"Abril", data:"17/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba44", nome:"Mayara Ferreira Marques", mes:"Abril", data:"20/04/2026", status:"Aprovado", obs:"" },
  { id:"aba45", nome:"JoÃ£o Roberto correa", mes:"Abril", data:"20/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba46", nome:"JoÃ£o Roberto correa", mes:"Abril", data:"20/04/2026", status:"Pendente", obs:"" },
  { id:"aba47", nome:"Eloisa Helena Costa de Campos", mes:"Abril", data:"20/04/2026", status:"Pendente", obs:"" },
  { id:"aba48", nome:"JÃ©ssica Miranda Bueno da Silva", mes:"Abril", data:"20/04/2026", status:"Faltou", obs:"" },
  { id:"aba49", nome:"Lorenzo Isbeler Silva", mes:"Abril", data:"22/04/2026", status:"Pendente", obs:"" },
  { id:"aba50", nome:"Lorena Macedo Mota", mes:"Abril", data:"22/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba51", nome:"Thiago AraÃºjo", mes:"Abril", data:"22/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba52", nome:"Felipe de Castro Silveira Lopes", mes:"Abril", data:"22/04/2026", status:"Pendente", obs:"" },
  { id:"aba53", nome:"Nilson Martins Silva", mes:"Abril", data:"23/04/2026", status:"Pendente", obs:"" },
  { id:"aba54", nome:"Silvana", mes:"Abril", data:"27/06/2026", status:"Faltou", obs:"" },
  { id:"aba55", nome:"Anna Laura Garcia", mes:"Abril", data:"27/04/200/26", status:"Aprovado", obs:"" },
  { id:"aba56", nome:"Ana Lidia Alves", mes:"Abril", data:"28/04/2026", status:"Aprovado", obs:"" },
  { id:"aba57", nome:"Maria Eduarda dos Santos", mes:"Abril", data:"29/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba58", nome:"Rebeca Isabelle", mes:"Abril", data:"29/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba59", nome:"Fabiana CAstilho", mes:"Abril", data:"30/04/2026", status:"Faltou", obs:"" },
  { id:"maa0", nome:"Bianca TainÃ¡", mes:"Maio", data:"05/04/2026", status:"Follow Up", obs:"" },
  { id:"maa1", nome:"Emerson Roberto", mes:"Maio", data:"05/04/2026", status:"Pendente", obs:"" },
  { id:"maa2", nome:"Ines de Souza", mes:"Maio", data:"05/05/2026", status:"Faltou", obs:"" },
  { id:"maa3", nome:"Aldo CÃ©sar", mes:"Maio", data:"05/06/2026", status:"Em Aberto", obs:"" },
  { id:"maa4", nome:"Silvana Alves", mes:"Maio", data:"05/06/2026", status:"Pendente", obs:"" },
  { id:"maa5", nome:"Fabiana Castilho", mes:"Maio", data:"05/06/2026", status:"Faltou", obs:"" },
  { id:"maa6", nome:"Othavio Henrique", mes:"Maio", data:"05/07/2026", status:"Follow Up", obs:"" },
  { id:"maa7", nome:"Josefa Severina", mes:"Maio", data:"05/07/2026", status:"Aprovado", obs:"" },
  { id:"maa8", nome:"Jaquiele ConceiÃ§Ã£o", mes:"Maio", data:"05/07/2026", status:"Pendente", obs:"" },
  { id:"maa9", nome:"Mariane souza da cruz", mes:"Maio", data:"13/05/2026", status:"Aprovado", obs:"" },
  { id:"maa10", nome:"Juliana Rocha rodrigues", mes:"Maio", data:"13/05/2026", status:"Em Aberto", obs:"" },
  { id:"maa11", nome:"Elzeli vicente da rocha", mes:"Maio", data:"13/05/2026", status:"Em Aberto", obs:"" },
  { id:"maa12", nome:"Adrian Ryan de Souza", mes:"Maio", data:"13/05/2026", status:"Faltou", obs:"" },
  { id:"maa13", nome:"Rafaela", mes:"Maio", data:"14/05/2026", status:"Pendente", obs:"" },
  { id:"maa14", nome:"MARINA ANTONIETA", mes:"Maio", data:"15/05/2026", status:"Pendente", obs:"" },
  { id:"maa15", nome:"Gabriela freitas da silva", mes:"Maio", data:"05/12/2026", status:"Pendente", obs:"" },
  { id:"maa16", nome:"Larissa Magiolo Geraldini", mes:"Maio", data:"15/05/2026", status:"Pendente", obs:"" },
  { id:"maa17", nome:"Janaina Martins Barbosa", mes:"Maio", data:"15/05/2026", status:"Pendente", obs:"" },
]
