export const PROCEDIMENTOS = [
  "Restauracoes","Limpezas","Clareamento","Cirurgias",
  "Implantes","Ortodontia","Invisa","Placas",
  "Lentes Porcelana","Lentes Resina","Endodontia","Proteses"
]

export const PROC_CFG = [
  { key:"Cirurgias",        color:"#dc2626", bg:"#fef2f2", label:"Cirurgias"        },
  { key:"Implantes",        color:"#7c3aed", bg:"#f5f3ff", label:"Implantes"        },
  { key:"Ortodontia",       color:"#1d6fd8", bg:"#eff6ff", label:"Ortodontia"       },
  { key:"Restauracoes",     color:"#0d9488", bg:"#f0fdfa", label:"Restauracoes"     },
  { key:"Limpezas",         color:"#16a34a", bg:"#f0fdf4", label:"Limpezas"         },
  { key:"Clareamento",      color:"#ca8a04", bg:"#fefce8", label:"Clareamento"      },
  { key:"Proteses",         color:"#ea580c", bg:"#fff7ed", label:"Proteses"         },
  { key:"Endodontia",       color:"#be185d", bg:"#fdf2f8", label:"Endodontia"       },
  { key:"Lentes Porcelana", color:"#0369a1", bg:"#f0f9ff", label:"Lentes Porcelana" },
  { key:"Lentes Resina",    color:"#4f46e5", bg:"#eef2ff", label:"Lentes Resina"    },
  { key:"Invisa",           color:"#0891b2", bg:"#ecfeff", label:"Invisalign"       },
  { key:"Placas",           color:"#65a30d", bg:"#f7fee7", label:"Placas"           },
]

export const STATUS_AV = ["Aprovado","Faltou","Em Aberto","Follow Up","Reprovado","Pendente"]

export const STATUS_CFG = {
  "Aprovado":  { color:"#16a34a", bg:"#f0fdf4", border:"#bbf7d0" },
  "Faltou":    { color:"#dc2626", bg:"#fef2f2", border:"#fecaca" },
  "Em Aberto": { color:"#7c3aed", bg:"#f5f3ff", border:"#ddd6fe" },
  "Follow Up": { color:"#1d6fd8", bg:"#eff6ff", border:"#bfdbfe" },
  "Reprovado": { color:"#be185d", bg:"#fdf2f8", border:"#fbcfe8" },
  "Pendente":  { color:"#ca8a04", bg:"#fefce8", border:"#fef08a" },
}

export const MESES = ["Janeiro","Fevereiro","Marco","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"]

export const SEED_PACIENTES = [
  { id:"jap0", nome:"José do Lago", mes:"Janeiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap1", nome:"Adriele Cheregati", mes:"Janeiro", procs:{"Restaurações":"16"}, feitos:{}, obs:"" },
  { id:"jap2", nome:"Jawad ataya", mes:"Janeiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap3", nome:"Alaa ataya", mes:"Janeiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap4", nome:"Geisy Kelli da Silva", mes:"Janeiro", procs:{"Restaurações":"11.12.14.1744.45", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap5", nome:"Liliana Andréia Guimarães", mes:"Janeiro", procs:{"Restaurações":"46", "Limpezas":"1", "Clareamento":"Gengivectimia", "Cirurgias":"25", "Ortodontia":"Estético", "Próteses":"Coroa Provisoria"}, feitos:{}, obs:"" },
  { id:"jap6", nome:"Ana Clara Gentil", mes:"Janeiro", procs:{"Restaurações":"13.14.24.16", "Limpezas":"1", "Ortodontia":"Estetico"}, feitos:{}, obs:"" },
  { id:"jap7", nome:"Rosa Helena Ferreira", mes:"Janeiro", procs:{"Restaurações":"18.28.27.25", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap9", nome:"Rodrigo Benatti Dias", mes:"Janeiro", procs:{"Restaurações":"47", "Limpezas":"1", "Cirurgias":"28", "Ortodontia":"Convensional"}, feitos:{}, obs:"" },
  { id:"jap10", nome:"Nathalie Prieto de Morais", mes:"Janeiro", procs:{"Restaurações":"11.16.17.12.22", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap11", nome:"Juliana Cristina Gino", mes:"Janeiro", procs:{"Restaurações":"14", "Limpezas":"1", "Cirurgias":"28.38"}, feitos:{}, obs:"" },
  { id:"jap12", nome:"Kevin Rian Fernandes", mes:"Janeiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap13", nome:"Itamar Soler Martins", mes:"Janeiro", procs:{"Restaurações":"26.17.", "Limpezas":"1", "Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"jap14", nome:"Livia Maria de Oliveira", mes:"Janeiro", procs:{"Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"jap15", nome:"Jozenilda dos Santos", mes:"Janeiro", procs:{}, feitos:{}, obs:"" },
  { id:"jap16", nome:"Eduardo Antônio Ferrari", mes:"Janeiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"jap17", nome:"Carlos Eduardo Módena", mes:"Janeiro", procs:{"Restaurações":"17.35", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep0", nome:"Paciente", mes:"Fevereiro", procs:{"Restaurações":"Restaurações", "Limpezas":"Limpezas", "Clareamento":"Clareamento", "Cirurgias":"Cirurgias", "Implantes":"Implantes", "Ortodontia":"Ortodontia", "Invisa":"Invisa", "Placas":"Placas", "Lentes Porcelana":"Lentes Porcelana", "Lentes Resina":"Lentes Resina", "Endodontia":"Endodontia", "Próteses":"Proteses"}, feitos:{}, obs:"" },
  { id:"fep1", nome:"Taina de Campos", mes:"Fevereiro", procs:{"Lentes Resina":"11.21"}, feitos:{}, obs:"" },
  { id:"fep2", nome:"Willian Gomes", mes:"Fevereiro", procs:{"Restaurações":"21.11.16.46", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep3", nome:"Henrique do Carmo", mes:"Fevereiro", procs:{"Lentes Porcelana":"25"}, feitos:{}, obs:"" },
  { id:"fep4", nome:"André Mariano", mes:"Fevereiro", procs:{"Limpezas":"1", "Lentes Resina":"23"}, feitos:{}, obs:"" },
  { id:"fep5", nome:"Bernardo Bergamin", mes:"Fevereiro", procs:{"Restaurações":"75", "Limpezas":"1", "Ortodontia":"Ortopedico"}, feitos:{}, obs:"" },
  { id:"fep6", nome:"Magna Oliveira", mes:"Fevereiro", procs:{"Restaurações":"23", "Endodontia":"23"}, feitos:{}, obs:"" },
  { id:"fep7", nome:"Bruno Eduardo Vieira", mes:"Fevereiro", procs:{"Limpezas":"1", "Ortodontia":"Contenção"}, feitos:{}, obs:"" },
  { id:"fep8", nome:"Maycon da Silva Barofe", mes:"Fevereiro", procs:{}, feitos:{}, obs:"" },
  { id:"fep9", nome:"Arthur Ernandes", mes:"Fevereiro", procs:{"Ortodontia":"Ortopedico"}, feitos:{}, obs:"" },
  { id:"fep10", nome:"Giovana Angélica Borin", mes:"Fevereiro", procs:{}, feitos:{}, obs:"" },
  { id:"fep11", nome:"Adriano Furigo", mes:"Fevereiro", procs:{"Restaurações":"21", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep12", nome:"Rosemary da Silva Teodoro", mes:"Fevereiro", procs:{"Restaurações":"46", "Limpezas":"1", "Lentes Resina":"11.21"}, feitos:{}, obs:"" },
  { id:"fep13", nome:"Evelin Lusa", mes:"Fevereiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep14", nome:"Gabriel Pires da Silva", mes:"Fevereiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep15", nome:"Beatriz Machado", mes:"Fevereiro", procs:{"Limpezas":"1", "Ortodontia":"Contenção"}, feitos:{}, obs:"" },
  { id:"fep16", nome:"Lyandra Santos Alves", mes:"Fevereiro", procs:{"Limpezas":"1", "Ortodontia":"Contenção"}, feitos:{}, obs:"" },
  { id:"fep17", nome:"Luma Barbara", mes:"Fevereiro", procs:{"Invisa":"Contenção"}, feitos:{}, obs:"" },
  { id:"fep18", nome:"Nathalia Bruna", mes:"Fevereiro", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep19", nome:"Josiane Cristina", mes:"Fevereiro", procs:{"Restaurações":"26.22.11", "Limpezas":"1", "Endodontia":"18"}, feitos:{}, obs:"" },
  { id:"fep20", nome:"Cicelio do Nascimento", mes:"Fevereiro", procs:{"Restaurações":"12.21.47.", "Limpezas":"2", "Clareamento":"1", "Cirurgias":"Por elemento", "Implantes":"45", "Lentes Resina":"11", "Endodontia":"35", "Próteses":"35"}, feitos:{}, obs:"" },
  { id:"fep21", nome:"Josuel dos Santos", mes:"Fevereiro", procs:{"Restaurações":"45.21", "Limpezas":"3"}, feitos:{}, obs:"" },
  { id:"fep22", nome:"Isabelly de Oliveira", mes:"Fevereiro", procs:{"Cirurgias":"48.28"}, feitos:{}, obs:"" },
  { id:"fep23", nome:"Lenita A. Scomparin", mes:"Fevereiro", procs:{"Implantes":"1"}, feitos:{}, obs:"" },
  { id:"fep24", nome:"Amanda Godoi", mes:"Fevereiro", procs:{"Restaurações":"36", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep25", nome:"Pedro Scomparin", mes:"Fevereiro", procs:{"Restaurações":"17.26.27.", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep26", nome:"Maicon Rafael", mes:"Fevereiro", procs:{"Limpezas":"1", "Invisa":"Contenção"}, feitos:{}, obs:"" },
  { id:"fep27", nome:"Rubens Moreira", mes:"Fevereiro", procs:{"Próteses":"22"}, feitos:{}, obs:"" },
  { id:"fep28", nome:"Robson Gimenez", mes:"Fevereiro", procs:{"Restaurações":"34.35.23.24.25.14.15.44.45.16.28.11.12.21.22", "Limpezas":"1", "Cirurgias":"46.27", "Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"fep29", nome:"Karina Martins", mes:"Fevereiro", procs:{"Lentes Porcelana":"31.32.33.34.35.41.42.43.44.45"}, feitos:{}, obs:"" },
  { id:"fep30", nome:"Anderson Pereira", mes:"Fevereiro", procs:{"Restaurações":"43.44.34.37.46.", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep31", nome:"Francisco Correa", mes:"Fevereiro", procs:{"Restaurações":"21.27.46", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"fep32", nome:"Bruno Henrique", mes:"Fevereiro", procs:{"Restaurações":"13.44.46.35.27.17", "Limpezas":"1", "Cirurgias":"38.48"}, feitos:{}, obs:"" },
  { id:"fep33", nome:"José Carlos Moreira", mes:"Fevereiro", procs:{"Cirurgias":"Tracionamento 23"}, feitos:{}, obs:"" },
  { id:"fep34", nome:"Robson Beserra", mes:"Fevereiro", procs:{"Invisa":"Contenção inf"}, feitos:{}, obs:"" },
  { id:"map0", nome:"Robinson Aparecido da Silva", mes:"Marco", procs:{"Restaurações":"11.21.26.36.31", "Limpezas":"1", "Cirurgias":"18.28.38.48", "Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"map1", nome:"Sérgio Luis da Silva", mes:"Marco", procs:{"Restaurações":"26.16.", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"map2", nome:"Giovana Angélica Borin", mes:"Marco", procs:{}, feitos:{}, obs:"" },
  { id:"map3", nome:"Simone Aparecida Secolin", mes:"Marco", procs:{}, feitos:{}, obs:"" },
  { id:"map4", nome:"Jean Moacir Casaril", mes:"Marco", procs:{"Restaurações":"36.26.17", "Limpezas":"1", "Lentes Resina":"13"}, feitos:{}, obs:"" },
  { id:"map5", nome:"Malak Badredeen", mes:"Marco", procs:{"Restaurações":"46.17"}, feitos:{}, obs:"" },
  { id:"map6", nome:"Beatriz Sales de Souza", mes:"Marco", procs:{}, feitos:{}, obs:"" },
  { id:"map7", nome:"Elis Regina Sousa", mes:"Marco", procs:{"Restaurações":"11.14.16.45..26,34.35.36.46", "Limpezas":"1", "Cirurgias":"18.28.38", "Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"map8", nome:"Rafaela Amaro de Carvalho", mes:"Marco", procs:{}, feitos:{}, obs:"" },
  { id:"map9", nome:"Joao Fernando Pangalde", mes:"Marco", procs:{"Restaurações":"12.13.21", "Limpezas":"1", "Cirurgias":"exo"}, feitos:{}, obs:"" },
  { id:"map10", nome:"Polyanna Barsotini Romanini", mes:"Marco", procs:{}, feitos:{}, obs:"" },
  { id:"map11", nome:"Edna Ferreira de Mello", mes:"Marco", procs:{}, feitos:{}, obs:"" },
  { id:"map12", nome:"Ana Lívia Faria da Silva", mes:"Marco", procs:{"Restaurações":"46.47.21.36.37.26", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"map13", nome:"Ester Aparecida Leonello", mes:"Marco", procs:{}, feitos:{}, obs:"" },
  { id:"map14", nome:"Josuel dos Santos Dias", mes:"Marco", procs:{"Restaurações":"43", "Endodontia":"43"}, feitos:{}, obs:"" },
  { id:"map15", nome:"Pietro Niller Mello", mes:"Marco", procs:{"Restaurações":"23", "Limpezas":"1", "Invisa":"lite"}, feitos:{}, obs:"" },
  { id:"map16", nome:"Diego Arita", mes:"Marco", procs:{"Restaurações":"46.15.37", "Limpezas":"1", "Cirurgias":"aumento de coroa"}, feitos:{}, obs:"" },
  { id:"map17", nome:"Maria Júlia Queiroz Bassetto", mes:"Marco", procs:{"Ortodontia":"Manutenção"}, feitos:{}, obs:"" },
  { id:"map18", nome:"Beatriz Machado", mes:"Marco", procs:{}, feitos:{}, obs:"" },
  { id:"map19", nome:"José Aparecido Balanciele", mes:"Marco", procs:{"Próteses":"Total"}, feitos:{}, obs:"" },
  { id:"map20", nome:"Suely Francisca S. Marineri", mes:"Marco", procs:{"Restaurações":"25.37.", "Limpezas":"1", "Cirurgias":"35"}, feitos:{}, obs:"" },
  { id:"map21", nome:"Eduardo Antônio Ferrari", mes:"Marco", procs:{"Limpezas":"1", "Cirurgias":"14", "Invisa":"Comprehensive", "Próteses":"Coroa Prov"}, feitos:{}, obs:"" },
  { id:"map22", nome:"Diego Arita", mes:"Marco", procs:{"Restaurações":"46.15.37", "Limpezas":"1", "Cirurgias":"Aumento coroa 37"}, feitos:{}, obs:"" },
  { id:"map23", nome:"Rafaela Amaro de Carvalho", mes:"Marco", procs:{"Restaurações":"25", "Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"map24", nome:"Liliana Andréia Guimarães", mes:"Marco", procs:{"Clareamento":"Caseiro/consultório"}, feitos:{}, obs:"" },
  { id:"map25", nome:"Cátia Gonçalves Cabral", mes:"Marco", procs:{"Limpezas":"1", "Lentes Resina":"15"}, feitos:{}, obs:"" },
  { id:"map26", nome:"Anderson Jesus Batista", mes:"Marco", procs:{"Restaurações":"26.17.11.22.24..24", "Limpezas":"1", "Próteses":"Coroa 16"}, feitos:{}, obs:"" },
  { id:"map27", nome:"Thais Soares de Lucema", mes:"Marco", procs:{"Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"map28", nome:"Lucia Moraes Porto", mes:"Marco", procs:{}, feitos:{}, obs:"" },
  { id:"map29", nome:"Roselena Patrícia Arantes", mes:"Marco", procs:{}, feitos:{}, obs:"" },
  { id:"map30", nome:"Weber Rodolfo Lopes", mes:"Marco", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"map31", nome:"Lucas Natan Mendes", mes:"Marco", procs:{"Restaurações":"17.27.35.11.21", "Limpezas":"1", "Cirurgias":"18.28.38.48", "Lentes Resina":"13.14.15.11.12.13."}, feitos:{}, obs:"" },
  { id:"map32", nome:"Thais Soares de Lucema", mes:"Marco", procs:{"Ortodontia":"Convencional", "Lentes Resina":"21.22.23.24.25"}, feitos:{}, obs:"" },
  { id:"map33", nome:"Andressa Cardoso", mes:"Marco", procs:{"Restaurações":"46.47"}, feitos:{}, obs:"" },
  { id:"map34", nome:"karina Teobaldo", mes:"Marco", procs:{"Ortodontia":"ontenção"}, feitos:{}, obs:"" },
  { id:"abp0", nome:"Vivian Gallego Arruda", mes:"Abril", procs:{"Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"abp1", nome:"Sérgio Luis da Silva", mes:"Abril", procs:{"Restaurações":"26.16", "Limpezas":"1", "Invisa":"Lite"}, feitos:{}, obs:"" },
  { id:"abp2", nome:"Asafe Emanuel Matos Gama", mes:"Abril", procs:{"Restaurações":"46.47.27", "Limpezas":"1", "Ortodontia":"Estético"}, feitos:{}, obs:"" },
  { id:"abp3", nome:"Ivanilda Leite de Souza Lima", mes:"Abril", procs:{"Restaurações":"45.25.26", "Limpezas":"1", "Clareamento":"1"}, feitos:{}, obs:"" },
  { id:"abp4", nome:"Leyla Cristina de Toledo", mes:"Abril", procs:{"Restaurações":"45.16"}, feitos:{}, obs:"" },
  { id:"abp5", nome:"Yasmin da Silva Noch", mes:"Abril", procs:{"Restaurações":"36.26.16", "Ortodontia":"Contenção inf"}, feitos:{}, obs:"" },
  { id:"abp6", nome:"Elane Cristina Cardoso", mes:"Abril", procs:{"Lentes Resina":"Dente13"}, feitos:{}, obs:"" },
  { id:"abp7", nome:"Clara Rodrigues", mes:"Abril", procs:{"Ortodontia":"Manutenção"}, feitos:{}, obs:"" },
  { id:"abp8", nome:"Luiza Odete Agostinho", mes:"Abril", procs:{"Restaurações":"21.37", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"abp9", nome:"Gislene Freitas de camargo", mes:"Abril", procs:{"Restaurações":"11.15.24.25", "Limpezas":"1", "Ortodontia":"Estéticio", "Endodontia":"25"}, feitos:{}, obs:"" },
  { id:"abp10", nome:"Izaias Moraes da Silva", mes:"Abril", procs:{"Restaurações":"36.337.47", "Limpezas":"1", "Clareamento":"1"}, feitos:{}, obs:"" },
  { id:"abp11", nome:"Jofran Santa Rosa Cruz", mes:"Abril", procs:{"Restaurações":"25", "Limpezas":"1", "Endodontia":"25"}, feitos:{}, obs:"" },
  { id:"abp12", nome:"Heytor dos Santos Xavier", mes:"Abril", procs:{"Ortodontia":"Ortopedico"}, feitos:{}, obs:"" },
  { id:"abp13", nome:"Jael Gomes Haine", mes:"Abril", procs:{"Restaurações":"16.37", "Limpezas":"1", "Cirurgias":"46.36"}, feitos:{}, obs:"" },
  { id:"abp14", nome:"Rosana Aparecida Lima", mes:"Abril", procs:{"Restaurações":"34", "Cirurgias":"34"}, feitos:{}, obs:"" },
  { id:"abp15", nome:"Laura Ernst Pitta", mes:"Abril", procs:{"Restaurações":"21"}, feitos:{}, obs:"" },
  { id:"abp16", nome:"Mylena Cristina Borges", mes:"Abril", procs:{"Restaurações":"35.36"}, feitos:{}, obs:"" },
  { id:"abp17", nome:"Adriano Pires Neto", mes:"Abril", procs:{"Restaurações":"12..14.47"}, feitos:{}, obs:"" },
  { id:"abp18", nome:"Vanessa de Souza Lima", mes:"Abril", procs:{"Restaurações":"15", "Limpezas":"1", "Cirurgias":"18.28.48"}, feitos:{}, obs:"" },
  { id:"abp19", nome:"Maria de Lourdes Carvalho", mes:"Abril", procs:{"Restaurações":"13.14.15.23.24.34.35.3645.44", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"abp20", nome:"Liliane Lima de Morais", mes:"Abril", procs:{"Limpezas":"1", "Lentes Resina":"11.21.22"}, feitos:{}, obs:"" },
  { id:"abp21", nome:"Matheus Barbosa da Silva", mes:"Abril", procs:{"Limpezas":"1", "Ortodontia":"Contenção"}, feitos:{}, obs:"" },
  { id:"abp22", nome:"Lucas Barbosa da Silva", mes:"Abril", procs:{"Limpezas":"1", "Ortodontia":"Contenção"}, feitos:{}, obs:"" },
  { id:"abp23", nome:"Carlos Joaquim Souza", mes:"Abril", procs:{"Ortodontia":"Ortopedico"}, feitos:{}, obs:"" },
  { id:"abp24", nome:"Kamile da Silva Persego", mes:"Abril", procs:{"Restaurações":"16.17.36", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"abp25", nome:"Mayara Ferreira Marques", mes:"Abril", procs:{"Restaurações":"11.21.17.24.", "Limpezas":"1", "Cirurgias":"18.38.48", "Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"abp26", nome:"João Carlos Elias de Campo", mes:"Abril", procs:{"Restaurações":"14.15.16.36.45", "Limpezas":"1", "Implantes":"21", "Endodontia":"23", "Próteses":"21 Coroa"}, feitos:{}, obs:"" },
  { id:"abp27", nome:"Luis Afonso Zorzetto Laurindo", mes:"Abril", procs:{"Restaurações":"14.15.35.3624.25.47", "Cirurgias":"28", "Invisa":"Lite"}, feitos:{}, obs:"" },
  { id:"abp28", nome:"Miria Aparecida Zorzetto", mes:"Abril", procs:{"Restaurações":"37", "Limpezas":"1", "Próteses":"12 emax"}, feitos:{}, obs:"" },
  { id:"abp29", nome:"Pâmella Maciel Rodrigues", mes:"Abril", procs:{"Restaurações":"16.17.27.36.37.47", "Limpezas":"1", "Cirurgias":"26", "Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"abp30", nome:"André Luiz Gozzi Joaquim", mes:"Abril", procs:{"Implantes":"21.23"}, feitos:{}, obs:"" },
  { id:"abp31", nome:"André Luiz Gozzi Joaquim", mes:"Abril", procs:{"Cirurgias":"Enxerto"}, feitos:{}, obs:"" },
  { id:"abp32", nome:"Vitor Hugo Rodrigues", mes:"Abril", procs:{"Restaurações":"26", "Endodontia":"26"}, feitos:{}, obs:"" },
  { id:"abp33", nome:"Adriana Ueda de Oliveira", mes:"Abril", procs:{"Invisa":"Contenção"}, feitos:{}, obs:"" },
  { id:"abp34", nome:"Geraldo Ferreira", mes:"Abril", procs:{"Próteses":"36 emax"}, feitos:{}, obs:"" },
  { id:"abp35", nome:"Maria Eugenia Martinho", mes:"Abril", procs:{"Restaurações":"32.31.33.13.21.23.41", "Cirurgias":"27.15", "Próteses":"Ppr"}, feitos:{}, obs:"" },
  { id:"abp36", nome:"Regiany Lucy Rodrigues", mes:"Abril", procs:{"Restaurações":"35.43", "Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"abp37", nome:"Paulo José Franco", mes:"Abril", procs:{"Implantes":"12.15", "Próteses":"11.12.13.14.15.21.22.  grampo"}, feitos:{}, obs:"" },
  { id:"abp38", nome:"Thiago Araújo", mes:"Abril", procs:{"Limpezas":"1", "Implantes":"46.26.", "Lentes Resina":"11.12.13.14.16.21.22.23.24."}, feitos:{}, obs:"" },
  { id:"abp39", nome:"Liliana Andréia Guimarães", mes:"Abril", procs:{"Limpezas":"1", "Próteses":"Coroa Provisoria dente 25"}, feitos:{}, obs:"" },
  { id:"abp40", nome:"Ana Lidia Alves da Anunciação", mes:"Abril", procs:{"Restaurações":"11.21.23.24.25.27", "Limpezas":"1", "Cirurgias":"48.18.38.", "Ortodontia":"Convencional", "Próteses":"36 emax"}, feitos:{}, obs:"" },
  { id:"abp41", nome:"Angelo Emilio de Toledo", mes:"Abril", procs:{"Limpezas":"1", "Próteses":"ajuste implante"}, feitos:{}, obs:"" },
  { id:"abp42", nome:"Inês Ferreira de Lima", mes:"Abril", procs:{"Limpezas":"1"}, feitos:{}, obs:"" },
  { id:"map0", nome:"Felipe de Castro Silveira", mes:"Maio", procs:{"Ortodontia":"Ortopedico"}, feitos:{}, obs:"" },
  { id:"map1", nome:"Diego Arita", mes:"Maio", procs:{}, feitos:{}, obs:"" },
  { id:"map2", nome:"Iolanda Ap. Gonçalves", mes:"Maio", procs:{"Lentes Resina":"17", "Próteses":"Coroa emax 46"}, feitos:{}, obs:"" },
  { id:"map3", nome:"Elizabethe de Melo", mes:"Maio", procs:{"Próteses":"Coroa 11"}, feitos:{}, obs:"" },
  { id:"map4", nome:"Ana Laura Borin", mes:"Maio", procs:{"Ortodontia":"Convencional"}, feitos:{}, obs:"" },
  { id:"map5", nome:"Aparecida Penha", mes:"Maio", procs:{}, feitos:{}, obs:"" },
  { id:"map6", nome:"Josefa severina Torres", mes:"Maio", procs:{"Limpezas":"1", "Clareamento":"1", "Cirurgias":"46", "Ortodontia":"Contenção"}, feitos:{}, obs:"" },
  { id:"map7", nome:"Charles Kelvin Paulino", mes:"Maio", procs:{"Restaurações":"14", "Endodontia":"14"}, feitos:{}, obs:"" },
  { id:"map8", nome:"Lenita A. Scomparin", mes:"Maio", procs:{}, feitos:{}, obs:"" },
  { id:"map9", nome:"José Carlos Blefari", mes:"Maio", procs:{}, feitos:{}, obs:"" },
  { id:"map10", nome:"Lucas Roberto", mes:"Maio", procs:{"Restaurações":"15.16.24.34.44.35", "Limpezas":"1", "Ortodontia":"Auto Ligado", "Próteses":"Coroa Prov 37"}, feitos:{}, obs:"" },
  { id:"map11", nome:"José Antonio Scomparin", mes:"Maio", procs:{}, feitos:{}, obs:"" },
  { id:"map12", nome:"Gabriel Pires da Silva", mes:"Maio", procs:{}, feitos:{}, obs:"" },
  { id:"map13", nome:"Celso Benatti", mes:"Maio", procs:{"Endodontia":"34", "Próteses":"Coroa emax 34"}, feitos:{}, obs:"" },
  { id:"map14", nome:"Liliana Andréia Guimarães", mes:"Maio", procs:{"Próteses":"Coroa 25"}, feitos:{}, obs:"" },
  { id:"map15", nome:"Mariane souza da cruz", mes:"Maio", procs:{"Restaurações":"16.17.36.37", "Limpezas":"1", "Clareamento":"Inferior", "Cirurgias":"Gengicevtomia", "Lentes Resina":"11.12.13.14.15.21.22.23.24.25"}, feitos:{}, obs:"" },
  { id:"map16", nome:"Denise Porto Pieroni", mes:"Maio", procs:{"Próteses":"Coroa 25.46."}, feitos:{}, obs:"" },
  { id:"map17", nome:"Inês Ferreira de Lima", mes:"Maio", procs:{"Restaurações":"13.31.35.41.46."}, feitos:{}, obs:"" },
  { id:"map18", nome:"Gabriella Christina Miguel", mes:"Maio", procs:{"Limpezas":"1", "Ortodontia":"Invisa"}, feitos:{}, obs:"" },
]

export const SEED_AVALIACOES = [
  { id:"jaa0", nome:"Maycon da Silva Barofe", mes:"Janeiro", data:"14/01/2026", status:"Pendente", obs:"" },
  { id:"jaa1", nome:"Rosa Helena Ferreira de", mes:"Janeiro", data:"14/01/2026", status:"Aprovado", obs:"" },
  { id:"jaa2", nome:"Gabriel Rossi", mes:"Janeiro", data:"14/01/2026", status:"Faltou", obs:"" },
  { id:"jaa3", nome:"Liliana Andréia Guimarães", mes:"Janeiro", data:"15/01/2025", status:"Aprovado", obs:"" },
  { id:"jaa4", nome:"Adriele Cheregati Fernandes", mes:"Janeiro", data:"15/01/2025", status:"Aprovado", obs:"" },
  { id:"jaa5", nome:"Geisy Kelli da Silva", mes:"Janeiro", data:"15/01/2026", status:"Aprovado", obs:"" },
  { id:"jaa6", nome:"Ana Clara Gentil", mes:"Janeiro", data:"15/01/2026", status:"Aprovado", obs:"" },
  { id:"jaa7", nome:"Itamar Soler", mes:"Janeiro", data:"20/01/2026", status:"Aprovado", obs:"" },
  { id:"jaa8", nome:"Luiz Fernando dos Santos", mes:"Janeiro", data:"21/01/2026", status:"Faltou", obs:"" },
  { id:"jaa9", nome:"Maria Cecília Ozanique", mes:"Janeiro", data:"22/01/2026", status:"Pendente", obs:"" },
  { id:"jaa10", nome:"Pedro Paulo Souza", mes:"Janeiro", data:"22/01/2026", status:"Faltou", obs:"" },
  { id:"jaa11", nome:"Livia Maria de Oliveira", mes:"Janeiro", data:"22/01/2026", status:"Aprovado", obs:"" },
  { id:"jaa12", nome:"Nathalie Prieto de Morais", mes:"Janeiro", data:"22/01/2026", status:"Aprovado", obs:"" },
  { id:"jaa13", nome:"Kilza Cristina Leite Mauch", mes:"Janeiro", data:"27/01/2026", status:"Pendente", obs:"" },
  { id:"fea0", nome:"Willian Gomes", mes:"Fevereiro", data:"02/04/2026", status:"Aprovado", obs:"" },
  { id:"fea1", nome:"Claudinei dos Santos", mes:"Fevereiro", data:"02/04/2026", status:"Pendente", obs:"" },
  { id:"fea2", nome:"Regina Celia Coser", mes:"Fevereiro", data:"02/05/2026", status:"Pendente", obs:"" },
  { id:"fea3", nome:"RobsonGimenez", mes:"Fevereiro", data:"02/05/2026", status:"Aprovado", obs:"" },
  { id:"fea4", nome:"Magna Oliveira Assis", mes:"Fevereiro", data:"02/10/2026", status:"Aprovado", obs:"" },
  { id:"fea5", nome:"Pedro T Neto", mes:"Fevereiro", data:"02/10/2026", status:"Pendente", obs:"" },
  { id:"fea6", nome:"Rafael Cesar da Mata", mes:"Fevereiro", data:"02/11/2026", status:"Pendente", obs:"" },
  { id:"fea7", nome:"Rosemery da Silva", mes:"Fevereiro", data:"02/11/2026", status:"Aprovado", obs:"" },
  { id:"fea8", nome:"José carlos Semolini", mes:"Fevereiro", data:"02/12/2026", status:"Pendente", obs:"" },
  { id:"fea9", nome:"Josuel Dos Santos", mes:"Fevereiro", data:"18/02/2026", status:"Pendente", obs:"" },
  { id:"fea10", nome:"Enrico Oliveira", mes:"Fevereiro", data:"19/02/2026", status:"Pendente", obs:"" },
  { id:"fea11", nome:"Isabely de Oliveira", mes:"Fevereiro", data:"19/02/2026", status:"Aprovado", obs:"" },
  { id:"fea12", nome:"Amanda Godoi", mes:"Fevereiro", data:"19/02/2026", status:"Pendente", obs:"" },
  { id:"fea13", nome:"Joao Fernando", mes:"Fevereiro", data:"19/02/2026", status:"Aprovado", obs:"" },
  { id:"fea14", nome:"Francisco Correia", mes:"Fevereiro", data:"26/02/2026", status:"Aprovado", obs:"" },
  { id:"fea15", nome:"Bruno Henrique", mes:"Fevereiro", data:"26/02/2026", status:"Pendente", obs:"" },
  { id:"fea16", nome:"Robson Beserra", mes:"Fevereiro", data:"26/02/2026", status:"Pendente", obs:"" },
  { id:"fea17", nome:"Julia  Rafhaela", mes:"Fevereiro", data:"26/02/2026", status:"Pendente", obs:"" },
  { id:"maa0", nome:"Mileny Silvana", mes:"Marco", data:"03/02/2026", status:"Pendente", obs:"" },
  { id:"maa1", nome:"Robinson Aparecido", mes:"Marco", data:"03/03/2026", status:"Aprovado", obs:"" },
  { id:"maa2", nome:"Sergio Luiz da Silva", mes:"Marco", data:"03/03/2026", status:"Pendente", obs:"" },
  { id:"maa3", nome:"Fatima Lima", mes:"Marco", data:"03/03/2026", status:"Reprovado", obs:"" },
  { id:"maa4", nome:"Jean Moacir", mes:"Marco", data:"03/03/2026", status:"Aprovado", obs:"" },
  { id:"maa5", nome:"Jael Gomes", mes:"Marco", data:"03/04/2026", status:"Faltou", obs:"" },
  { id:"maa6", nome:"Neide de Oliveira", mes:"Marco", data:"03/05/2026", status:"Faltou", obs:"" },
  { id:"maa7", nome:"Elis Regina Souza", mes:"Marco", data:"03/10/2026", status:"Aprovado", obs:"" },
  { id:"maa8", nome:"Diego Ariate", mes:"Marco", data:"03/10/2026", status:"Aprovado", obs:"" },
  { id:"maa9", nome:"Ester Aparecida Leonello", mes:"Marco", data:"16/03", status:"Aprovado", obs:"" },
  { id:"maa10", nome:"Pietro Niller Mello de Campos", mes:"Marco", data:"16/03", status:"Aprovado", obs:"" },
  { id:"maa11", nome:"Cátia Gonçalves Cabral", mes:"Marco", data:"—", status:"Aprovado", obs:"" },
  { id:"maa12", nome:"José Aparecido Balanciele", mes:"Marco", data:"—", status:"Aprovado", obs:"" },
  { id:"maa13", nome:"Guilherme Augusto Gregório", mes:"Marco", data:"—", status:"Pendente", obs:"" },
  { id:"maa14", nome:"Carlos Joaquim Souza Peixoto", mes:"Marco", data:"24/04/2026", status:"Pendente", obs:"" },
  { id:"maa15", nome:"Gabriel Joshua Zacarioto", mes:"Marco", data:"25/04/2026", status:"Pendente", obs:"" },
  { id:"maa16", nome:"Weber Rodolfo Lopes", mes:"Marco", data:"—", status:"Pendente", obs:"" },
  { id:"maa17", nome:"Daiane Martins", mes:"Marco", data:"31/03/2026", status:"Pendente", obs:"" },
  { id:"maa18", nome:"Maria Clara Martins Ferreira", mes:"Marco", data:"31/03/2026", status:"Pendente", obs:"" },
  { id:"maa19", nome:"Silvio Candido da Silvia Junior", mes:"Marco", data:"31/03/2026", status:"Pendente", obs:"" },
  { id:"aba0", nome:"Vivian Gallego Arruda", mes:"Abril", data:"04/01/2026", status:"Aprovado", obs:"" },
  { id:"aba1", nome:"Jhony Guimarães Evangelista", mes:"Abril", data:"04/01/2026", status:"Pendente", obs:"" },
  { id:"aba2", nome:"Thalisson Guedes", mes:"Abril", data:"04/01/2026", status:"Faltou", obs:"" },
  { id:"aba3", nome:"Caio lucn delfino", mes:"Abril", data:"04/02/2026", status:"Faltou", obs:"" },
  { id:"aba4", nome:"Ana Paula delfino", mes:"Abril", data:"04/02/2026", status:"Faltou", obs:"" },
  { id:"aba5", nome:"Asafe Emanuel Matos Gama", mes:"Abril", data:"04/02/2026", status:"Aprovado", obs:"" },
  { id:"aba6", nome:"Lucas Roberto da silva", mes:"Abril", data:"04/02/2026", status:"Pendente", obs:"" },
  { id:"aba7", nome:"Ivanilda Leite de Souza Lima", mes:"Abril", data:"04/06/2026", status:"Aprovado", obs:"" },
  { id:"aba8", nome:"Liliane lima de morais e Silva", mes:"Abril", data:"04/06/2026", status:"Pendente", obs:"" },
  { id:"aba9", nome:"Michelângelo Dalaqua arruda", mes:"Abril", data:"04/06/2026", status:"Pendente", obs:"" },
  { id:"aba10", nome:"Matheus Gallego arruda", mes:"Abril", data:"04/06/2026", status:"Pendente", obs:"" },
  { id:"aba11", nome:"Luiza Odete Agostinho da Silva", mes:"Abril", data:"04/07/2026", status:"Aprovado", obs:"" },
  { id:"aba12", nome:"Vanessa de Souza Lima", mes:"Abril", data:"04/04/2026", status:"Pendente", obs:"" },
  { id:"aba13", nome:"Ivanildo Ramos", mes:"Abril", data:"04/08/2026", status:"Faltou", obs:"" },
  { id:"aba14", nome:"Livia Ramos", mes:"Abril", data:"04/08/2026", status:"Faltou", obs:"" },
  { id:"aba15", nome:"Gabriel Bella", mes:"Abril", data:"04/08/2026", status:"Em Aberto", obs:"" },
  { id:"aba16", nome:"Maria Eugenia Martinho", mes:"Abril", data:"04/08/2026", status:"Pendente", obs:"" },
  { id:"aba17", nome:"Marcelo Teixeira da Silva", mes:"Abril", data:"04/08/2026", status:"Pendente", obs:"" },
  { id:"aba18", nome:"Isabel dos Santos Henrique", mes:"Abril", data:"04/08/2026", status:"Pendente", obs:"" },
  { id:"aba19", nome:"Silvia Regina Rolla Carneiro", mes:"Abril", data:"04/08/2026", status:"Pendente", obs:"" },
  { id:"aba20", nome:"Miria Aparecida Zorzetto", mes:"Abril", data:"04/08/2026", status:"Aprovado", obs:"" },
  { id:"aba21", nome:"Gislene Freitas de camargo", mes:"Abril", data:"04/09/2026", status:"Aprovado", obs:"" },
  { id:"aba22", nome:"Izaias Moraes da Silva", mes:"Abril", data:"04/09/2026", status:"Aprovado", obs:"" },
  { id:"aba23", nome:"Lilian Damaceno", mes:"Abril", data:"13/04/2026", status:"Pendente", obs:"" },
  { id:"aba24", nome:"Jael Gomes Haine", mes:"Abril", data:"14/04/2026", status:"Aprovado", obs:"" },
  { id:"aba25", nome:"Pâmella Maciel Rodrigues", mes:"Abril", data:"14/04/2026", status:"Aprovado", obs:"" },
  { id:"aba26", nome:"Ivone Mario Alvarenga", mes:"Abril", data:"14/04/2026", status:"Faltou", obs:"" },
  { id:"aba27", nome:"Zilda Aparecida Fátima Moraes", mes:"Abril", data:"14/04/2026", status:"Faltou", obs:"" },
  { id:"aba28", nome:"Caique Silverio Dourado", mes:"Abril", data:"14/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba29", nome:"Caio Ichiro Arita", mes:"Abril", data:"14/04/2026", status:"Pendente", obs:"" },
  { id:"aba30", nome:"Valquíria Esteves Nogueira", mes:"Abril", data:"15/04/2026", status:"Pendente", obs:"" },
  { id:"aba31", nome:"Suelen Dionísio de Souza", mes:"Abril", data:"15/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba32", nome:"Ednei Azevedo de Souza", mes:"Abril", data:"15/04/2026", status:"Pendente", obs:"" },
  { id:"aba33", nome:"Maria de Lourdes Carvalho", mes:"Abril", data:"16/04/2026", status:"Pendente", obs:"" },
  { id:"aba34", nome:"Aparecida de Fátima", mes:"Abril", data:"16/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba35", nome:"Luzia de Cássia Fernandes", mes:"Abril", data:"16/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba36", nome:"Liliane Lima de Morais e Silva", mes:"Abril", data:"16/04/2026", status:"Aprovado", obs:"" },
  { id:"aba37", nome:"Regiany Lucy Rodrigues", mes:"Abril", data:"16/04/2026", status:"Aprovado", obs:"" },
  { id:"aba38", nome:"Carolina Cassia Pereira", mes:"Abril", data:"17/04/2026", status:"Pendente", obs:"" },
  { id:"aba39", nome:"João Paulo", mes:"Abril", data:"17/04/2026", status:"Faltou", obs:"" },
  { id:"aba40", nome:"João Carlos Elias de Campo", mes:"Abril", data:"17/04/2026", status:"Pendente", obs:"" },
  { id:"aba41", nome:"Ruan Ferreira de Souza", mes:"Abril", data:"17/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba42", nome:"Daiana Andrade conceição", mes:"Abril", data:"17/04/2026", status:"Faltou", obs:"" },
  { id:"aba43", nome:"Luzia bisotto de Carvalho", mes:"Abril", data:"17/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba44", nome:"Mayara Ferreira Marques", mes:"Abril", data:"20/04/2026", status:"Aprovado", obs:"" },
  { id:"aba45", nome:"João Roberto correa", mes:"Abril", data:"20/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba46", nome:"João Roberto correa", mes:"Abril", data:"20/04/2026", status:"Pendente", obs:"" },
  { id:"aba47", nome:"Eloisa Helena Costa de Campos", mes:"Abril", data:"20/04/2026", status:"Pendente", obs:"" },
  { id:"aba48", nome:"Jéssica Miranda Bueno da Silva", mes:"Abril", data:"20/04/2026", status:"Faltou", obs:"" },
  { id:"aba49", nome:"Lorenzo Isbeler Silva", mes:"Abril", data:"22/04/2026", status:"Pendente", obs:"" },
  { id:"aba50", nome:"Lorena Macedo Mota", mes:"Abril", data:"22/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba51", nome:"Thiago Araújo", mes:"Abril", data:"22/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba52", nome:"Felipe de Castro Silveira Lopes", mes:"Abril", data:"22/04/2026", status:"Pendente", obs:"" },
  { id:"aba53", nome:"Nilson Martins Silva", mes:"Abril", data:"23/04/2026", status:"Pendente", obs:"" },
  { id:"aba54", nome:"Silvana", mes:"Abril", data:"27/06/2026", status:"Faltou", obs:"" },
  { id:"aba55", nome:"Anna Laura Garcia", mes:"Abril", data:"27/04/200/26", status:"Aprovado", obs:"" },
  { id:"aba56", nome:"Ana Lidia Alves", mes:"Abril", data:"28/04/2026", status:"Aprovado", obs:"" },
  { id:"aba57", nome:"Maria Eduarda dos Santos", mes:"Abril", data:"29/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba58", nome:"Rebeca Isabelle", mes:"Abril", data:"29/04/2026", status:"Em Aberto", obs:"" },
  { id:"aba59", nome:"Fabiana CAstilho", mes:"Abril", data:"30/04/2026", status:"Faltou", obs:"" },
  { id:"maa0", nome:"Bianca Tainá", mes:"Maio", data:"05/04/2026", status:"Follow Up", obs:"" },
  { id:"maa1", nome:"Emerson Roberto", mes:"Maio", data:"05/04/2026", status:"Pendente", obs:"" },
  { id:"maa2", nome:"Ines de Souza", mes:"Maio", data:"05/05/2026", status:"Faltou", obs:"" },
  { id:"maa3", nome:"Aldo César", mes:"Maio", data:"05/06/2026", status:"Em Aberto", obs:"" },
  { id:"maa4", nome:"Silvana Alves", mes:"Maio", data:"05/06/2026", status:"Pendente", obs:"" },
  { id:"maa5", nome:"Fabiana Castilho", mes:"Maio", data:"05/06/2026", status:"Faltou", obs:"" },
  { id:"maa6", nome:"Othavio Henrique", mes:"Maio", data:"05/07/2026", status:"Follow Up", obs:"" },
  { id:"maa7", nome:"Josefa Severina", mes:"Maio", data:"05/07/2026", status:"Aprovado", obs:"" },
  { id:"maa8", nome:"Jaquiele Conceição", mes:"Maio", data:"05/07/2026", status:"Pendente", obs:"" },
  { id:"maa9", nome:"Mariane souza da cruz", mes:"Maio", data:"13/05/2026", status:"Aprovado", obs:"" },
  { id:"maa10", nome:"Juliana Rocha rodrigues", mes:"Maio", data:"13/05/2026", status:"Em Aberto", obs:"" },
  { id:"maa11", nome:"Elzeli vicente da rocha", mes:"Maio", data:"13/05/2026", status:"Em Aberto", obs:"" },
  { id:"maa12", nome:"Adrian Ryan de Souza", mes:"Maio", data:"13/05/2026", status:"Faltou", obs:"" },
  { id:"maa13", nome:"Rafaela", mes:"Maio", data:"14/05/2026", status:"Pendente", obs:"" },
  { id:"maa14", nome:"MARINA ANTONIETA", mes:"Maio", data:"15/05/2026", status:"Pendente", obs:"" },
  { id:"maa15", nome:"Gabriela freitas da silva", mes:"Maio", data:"05/12/2026", status:"Pendente", obs:"" },
  { id:"maa16", nome:"Larissa Magiolo Geraldini", mes:"Maio", data:"15/05/2026", status:"Pendente", obs:"" },
  { id:"maa17", nome:"Janaina Martins Barbosa", mes:"Maio", data:"15/05/2026", status:"Pendente", obs:"" },
]
